### ISSUE TITLE
Overlapping touch areas in the molecule selection panel

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#101]
The touch areas in the molecule selection panel overlap with one another, see screenshot below.

![mal-overlapping-touch-areas](https://cloud.githubusercontent.com/assets/3082831/6698546/18d0fb44-ccbf-11e4-9ff7-2086b057d12a.png)

**Comment by jessegreenberg** [comment]
RadioButtonGroup has options for setting the x and y touch area expansions and their default values are both 5.  For tightly stacked radioButtonGroups, this will cause the touch areas to overlap.  I set the touch area expansion values to 0 and the buttons now look like this:

![capture](https://cloud.githubusercontent.com/assets/6396244/6703184/2f5b55e2-ccfd-11e4-9e7e-620723d7ba19.PNG)

Reassigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks great.  I tested it on an iPad 2 and it works well.  Closing.
