### ISSUE TITLE
Error message and assertion for reset in some situations

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#103]
This problem occurs on the current master and the  on http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.9/molecules-and-light_en.html as an error message.  The dev.9 version is the only one I tested, this probably exists on others as well.

To duplicate, start the sim, switch the molecule to ozone and the emitter to UV.  As soon as the molecule breaks apart, press the reset button.  The sim will hit an assertion when running in RequireJS mode with assertions enabled.  It will output an error message on built versions.

This screenshot shows the sim setup when the assertion is hit:

![mal-reset-assertion](https://cloud.githubusercontent.com/assets/3082831/6716119/bcca0872-cd68-11e4-96e0-b634b51a8685.png)

**Comment by jessegreenberg** [comment]
This should be fixed with the commit above.  Molecule's setVibration function should not have assertions or error statements so that it still works for molecules that don't have vibration behavior.  I have fixed the function so that it behaves exactly as it does in the Java.

**Comment by jbphet** [comment]
Looks good - closing.
