### ISSUE TITLE
Photons often disappear when switching from landscape to portrait mode on iPad

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#105]
This was duplicated both on an iPad 2 running iOS 7.0.4 and an iPad 3 running iOS 8.1.  If you set up a situation where a stream of photons is coming out while the iPad is in landscape mode, then reorient the iPad to be in portrait mode, the photons disappear, but their affects still occur.

This is being seen on the current master, and similar behavior is seen on the published dev versions.

**Comment by jbphet** [comment]
Screenshot below.  Photons should be visible, but aren't.  The molecule is glowing, indicating that it just absorbed a photon, so the model is still working.

![mal-photons-disappear](https://cloud.githubusercontent.com/assets/3082831/6758958/cea0cf3c-cf01-11e4-90f1-ff12a6588f35.PNG)

If I switch to a different photon emitter, the visible light photons reappear as they move off the screen to the right.  The screenshot below captures the moment just after switching to the UV emitter:

![mal-viz-photons-reappear](https://cloud.githubusercontent.com/assets/3082831/6758993/2292acb4-cf02-11e4-80fa-b22f66443f68.PNG)

**Comment by jbphet** [comment]
This can be duplicated on Safari + Mac OSX by resizing the window while setting the sim up as described above (@jonathanolson suggested trying this).  For reference, the particular setup was the Mac named "Dirac", Safari version 8.0, OSX version 10.10.1.

**Comment by jonathanolson** [comment]
Interestingly, I can reproduce this on the Macbook Air, but after resizing the particles freeze in place, and start disappearing in order (the right-most one disappears, then a second later the next-right-most disappears, etc. until they are all gone).

Additionally, after resizing again (even while they are not displayed), it sets all of them to visible and starts the process again.

Continuously resizing will keep the photons animating in the correct locations. Additionally, there are certain sizes (609x616) where resizing doesn't seem to cause things to disappear, but other sizes (505x616) which are guaranteed to make things disappear.

**Comment by jonathanolson** [comment]
Also after pausing script execution (after they have disappeared), deleting the div directly after the problematic SVG causes them to reappear. Will investigate why (putting it back doesn't make them disappear again).

**Comment by jonathanolson** [comment]
Removing the clipArea causes the bug to vanish. It's almost like the clipArea is moving to the left each frame after things get resized.

Looks like a Safari-specific SVG bug relating to clipping.

**Comment by jonathanolson** [comment]
My best recommended workaround is to not use clipping, and instead fill the area around the "clip area" with the background color of the sim (maybe with a stroked rectangle) that will cover up any photons outside the desired area, and then have the border displayed above that.

I wasn't able to find any bug documentation about this, but just unsolved reports of "SVG things disappear" sometimes in Safari, with weird workarounds (not using strokes, etc.).

**Comment by jessegreenberg** [comment]
Thanks or the recommendation @jonathanolson, I have layered a stroked rectangle in place of the clipping area as you suggest above.  I tested this on my iPad2 (iOS 8.2) and it fixes the bug.

I have added some documentation in the code describing this as a temporary workaround.

Reassigning to @jbphet for review.

**Comment by jbphet** [comment]
Commit looks good and the behavior is now fine on my iPad 2.  Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by jbphet** [comment]
The automatic re-opening of this issue was due to two TODOs in the code about using a layered rectangle instead of a clipping area due to a Safari-specific bug.  The next thing to do would be to try the clipping area and see if the problem is gone.  This isn't a high priority, so I'll just do it sometime when I can sneak it in.

**Comment by jbphet** [comment]
I restored the clipping rectangle and removed the workaround (i.e. the stroked rectangle around the border), then regression tested on Chrome and Firefox on my Windows 11 machine. I then tested on an iPad 8 (model A2270) running iOS 17.5.1, rotating the device several times, and everything looked good.  Next, I tested on a MacBook Pro - Denzell's old one - running MacOS Ventura 13.7, and resized the window while emitting photons.  It all looked fine.

@KatieWoe - Could you please have QA verify this fix on a few more devices, mostly focused on Safari?  If everything looks good (no missing photons and no photons going beyond the borders of the observation window), this can be closed.

**Comment by Nancy-Salpepi** [comment]
I'm not seeing any issues with my MacBook Air macOS 15.1.1 + safari 18.1.1 or iPad 9th generation with iPadOS 18.0.1.

**Comment by KatieWoe** [comment]
I didn't see the problem either on iPad 10th gen with iPadOS 18.1.1. I should note that I wasn't able to reproduce it on the same device when looking at published.

**Comment by Ashton-Morris** [comment]
Tested on iPad Pro 4th-gen with 18.0 and did not see any issues.

**Comment by jbphet** [comment]
Thanks QA - sound like we can close.  One item of note first though.  Above, @KatieWoe said:

> I should note that I wasn't able to reproduce it on the same device when looking at published.

This is as expected, since that version was publish with the workaround that I removed as part of this work.

Closing.
