### ISSUE TITLE
pointer areas overlap with longer strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#106]
1.0.0-dev.10, all platforms, with the following query parameters:

http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.10/molecules-and-light_en.html?stringTest=double&showPointerAreas

There is significant overlap of point areas (touch and mouse) between the 4 "lamp" radio buttons and the "Show Light Spectrum" button, see screen shot below.  Since there is no overlap with English strings, I'm guessing that the computation of the pointer areas is not adaptive.

![screenshot_488](https://cloud.githubusercontent.com/assets/3046552/6761425/9036ebde-cf18-11e4-8648-74b86c41ebc1.png)

**Comment by jessegreenberg** [comment]
Sorry about that, this should be fixed with the commit above.  This is what it looks like now:

![capture](https://cloud.githubusercontent.com/assets/6396244/6792136/c9cc193c-d17a-11e4-8a12-01cef1a53ada.PNG)

Reassigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks good, closing.
