### ISSUE TITLE
"Show Light Spectrum" dialog will not reopen if you closed it by clicking outside the dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#107]
1.0.0-dev.10, all plaforms.

http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.10/molecules-and-light_en.html

Steps to reproduce:
1. Start the sim.
2. Press the "Show Light Spectrum" button, the dialog opens.
3. Click the "Close" button, the dialog closes.
4. Press the "Show Light Spectrum" button, the dialog opens.
5. Click anywhere on the screen (but not on the Close button), the dialog closes.
6. Press the "Show Light Spectrum" button. The dialog does not open, and never will.

**Comment by jessegreenberg** [comment]
Thank you for catching this!  I think I have isolated this to an issue in joist, which I have described in a ticket here: phetsims/joist#229.

Otherwise, I am using Dialog incorrectly, in which case I apologize.  I will wait to pursue this further until phetsims/joist#229 is reviewed.

**Comment by arouinfar** [comment]
This issue appears to be resolved in 1.0.0-rc.1

**Comment by jbphet** [comment]
Indeed, this was resolved by fixing https://github.com/phetsims/joist/issues/229 in the joist repo.  Closing.
