### ISSUE TITLE
Update Design Team Credits

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecules-and-light#108]
The convention for crediting the lead design on a port is to list both the original lead on the Java/Flash sim and the lead designer for the HTML5 version. Please update the lead design credit to read: Kelly Lancaster (Java), Amy Rouinfar (HTML5)

Since the lead designer is not repeated in the team credits, please remove Amy Rouinfar from the Team section. Yuen-ying Carpenter and Emily Moore are also missing from the team credits and should be added.

**Comment by arouinfar** [comment]
I've noticed that the QA team is also missing from the credits.

**Comment by jessegreenberg** [comment]
I have updated the team credits, now it looks like this: 

![capture](https://cloud.githubusercontent.com/assets/6396244/6998836/e91ad02c-dbab-11e4-8965-37f32999ce7a.PNG)

@arouinfar are these the correct names for the QA team?

**Comment by arouinfar** [comment]
Looks great! Closing.
