### ISSUE TITLE
Molecules spawn with bonds in opposite locations

### ISSUE THREAD

**Issue by bryo5363** [phetsims/molecules-and-light#109]
Test device: MacBook Pro

Operating System: 10.10.1

Browser: Chrome 41.0.2272.104 (64-bit)

Problem description: When using the ultraviolet lamp w/ molecules that have multiple bonds, sometimes the molecule will respawn with bonds in the opposite location. 

Steps to reproduce:
-open sim
-select ultraviolet lamp
-select bent molecule w/ two bonds
-break the bonds
-press return molecule. sometimes the molecule will appear to have it's bonds in the opposite location
Severity:

Screenshots:
![screen shot 2015-04-02 at 10 13 59 am](https://cloud.githubusercontent.com/assets/7717368/6968110/5d1ee78e-d921-11e4-8213-6a7230750b9c.png)

![screen shot 2015-04-02 at 10 17 02 am](https://cloud.githubusercontent.com/assets/7717368/6968140/8192ef70-d921-11e4-9aa2-b1af7b6f26f8.png)

Troubleshooting information (do not edit):
Name: Molecules and Light
URL: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-rc.1/molecules-and-light_en.html
Version: 1.0.0-rc.1
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36
Language: en-US
Window: 1210x567
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by arouinfar** [comment]
This is intentional behavior, @bryo5363, but good observation. Ozone and nitrogen dioxide both have resonance bonding, so we randomly choose which side will have the "double" bond.
