### ISSUE TITLE
Photon recentering interferes with playback

### ISSUE THREAD

**Issue by samreid** [phetsims/molecules-and-light#114]
While instrumenting the sim for tandem, I saw this code in ObservationWindow.js

```js
// Set up the event listeners for adding and removing photons.
photonAbsorptionModel.photons.addItemAddedListener( function( addedPhoton ) {
  var photonNode = new PhotonNode( addedPhoton, thisWindow.modelViewTransform );
  photonNode.center = ( modelViewTransform.modelToViewPosition( photonAbsorptionModel.getPhotonEmissionLocation() ) );
  photonLayer.addChild( photonNode );
  //...
}
```

PhotonNode sets the position by linking to the property, but it is overriden by this line:
```js
photonNode.center = ( modelViewTransform.modelToViewPosition( photonAbsorptionModel.getPhotonEmissionLocation() ) );
```

thus preventing loading the positions of photons.  Can that line be eliminated?  I tried removing it and the sim seemed to function properly.

**Comment by samreid** [comment]
I removed the line in question above so that I can proceed with #112 but it would be great to hear from @jessegreenberg if that line was doing something important or if it is okay to be removed.

**Comment by jessegreenberg** [comment]
Yes, I think this line was excessive and a mistake.  Sorry about that. Closing.
