### ISSUE TITLE
Update may not work correctly on Safari

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#118]
We are getting ready to deploy this simulation for the Summer 2015 Redeploy.  There is a known issue with the update-checking feature with Safari, see https://github.com/phetsims/website/issues/259.  There is a chance (@jonathanolson estimates 10-20%) that a code change may be required in the common code, so we shouldn't do the redeploy until the issue is resolved.  

This issue in molecules-and-light is essentially a reminder to not redeploy until the update-checking issue is fully resolved.

**Comment by jonathanolson** [comment]
I believe this should be fixed after there's a website deployment.

**Comment by jbphet** [comment]
I will leave this open for now and assign to myself, and once we have a release candidate I'll assign it to one of the QA people in order to make sure that it is thoroughly tested.

**Comment by jbphet** [comment]
Assigning to @phet-steele to verify on the latest release candidate for this sim.

**Comment by phet-steele** [comment]
Verified as good, at least as far as no problems when running with ?ea.
