### ISSUE TITLE
Light Spectrum w/ Long String Test on iPad

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/molecules-and-light#120]
Test device: iPad 2

Operating System: iOS 8.3

Browser: Safari

Problem description: Light Spectrum window is larger than the screen dimensions when the Long String Test is used. 

Steps to reproduce: Perform extremely long string test. Open Light Spectrum display. 

Severity: 

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/9257271/e47abfd4-41b1-11e5-8f5f-5bb8b91c37f9.jpg)

Troubleshooting information (do not edit):
Name: SomeExtremelyLongStringThatWouldLikelyBreakAnythingDoubleDidNotExpose
URL: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.1/molecules-and-light_en.html?stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingDoubleDidNotExpose
Version: 1.1.0-rc.1 2015-08-11 18:49:22 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1f0ca9f4","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"aa39bc48","branch":"master"},"chipper":{"sha":"6cb12b9c","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"77298536","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"molecules-and-light":{"sha":"05c075b5","branch":"1.1"},"nitroglycerin":{"sha":"c6f79ce4","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"e23c0f08","branch":"master"},"scenery-phet":{"sha":"bec2cc7f","branch":"master"},"sherpa":{"sha":"4f160877","branch":"master"},"sun":{"sha":"66c091cc","branch":"master"}}

**Comment by jessegreenberg** [comment]
This should be fixed the commit above.  Spectrum window now looks like the following with very long strings:

![stringtestextremelylong](https://cloud.githubusercontent.com/assets/6396244/9280889/a4629c1e-427e-11e5-8e85-a754e6371e77.PNG)

And looks like the following with stringTest=double:

![stringtestdouble](https://cloud.githubusercontent.com/assets/6396244/9280899/ab425b82-427e-11e5-8bb1-fddff5d73780.PNG)

Fix will be published in next release candidate.

**Comment by jessegreenberg** [comment]
This issue has been resolved and the fix was verified in https://github.com/phetsims/tasks/issues/332.  Closing.
