### ISSUE TITLE
create a new release candidate (1.1.0-rc.3) to pick up some recent changes

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#123]
In the 8/27/2015 meetings, it was decided that the 1.1 release of this sim should be delayed to pick up the fixes for the following issues: 
+ https://github.com/phetsims/joist/issues/295
+ https://github.com/phetsims/joist/issues/296
+ https://github.com/phetsims/phet-edmodo/issues/2

**Comment by jbphet** [comment]
We also want to pick up this one:

+ https://github.com/phetsims/chipper/issues/330

...and we might as well get this one too, since it affects the way directional formatting for strings is added, and it would be good to make sure that the sims all handle it the same way.

+ https://github.com/phetsims/chipper/issues/332

**Comment by jessegreenberg** [comment]
Patches to chipper and joist have been applied to 1.1.  molecules-and-light 1.1.0-rc.3 has been deployed on spot.  Closing.
