### ISSUE TITLE
Copyright statement should say "University of Colorado Boulder"

### ISSUE THREAD

**Issue by samreid** [phetsims/molecules-and-light#125]
While I was looking at https://github.com/phetsims/chipper/issues/235 I noticed that the copyright statements in molecules-and-light read:
```js
// Copyright 2002-2015, University of Colorado
```

The legal entity name of the university is University of Colorado Boulder so the comments should read like this:
```js
// Copyright 2002-2015, University of Colorado Boulder
```

**Comment by jessegreenberg** [comment]
Thanks for the catch, copyright statements updated and fixed in commit above.
