### ISSUE TITLE
OSX 10.11 FF text "dimming"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecules-and-light#126]
Testing on OSX 10.11 and FF 41.0.2, the molecule selection panel text will "dim" when scrolling the mouse over them quickly (but NOT while moving slowly). Sim state shouldn't affect reproducibilty. Tested on Dirac.

Video:
https://drive.google.com/file/d/0B3HJopSo_QqLRFplUnVzTVA1Wlk/view?usp=sharing

Troubleshooting information:
Name: ‪Molecules and Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.4/molecules-and-light_en.html
Version: 1.1.0-rc.4 2015-10-27 22:18:33 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:41.0) Gecko/20100101 Firefox/41.0
Language: en-US
Window: 1207x585
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"HEAD"},"axon":{"sha":"e2237347","branch":"HEAD"},"babel":{"sha":"196b8945","branch":"master"},"brand":{"sha":"8a756e53","branch":"HEAD"},"chipper":{"sha":"157b9cf3","branch":"HEAD"},"dot":{"sha":"d99cbe46","branch":"HEAD"},"joist":{"sha":"121bb0de","branch":"HEAD"},"kite":{"sha":"40dc703a","branch":"HEAD"},"molecules-and-light":{"sha":"d9fab288","branch":"HEAD"},"nitroglycerin":{"sha":"d7c8f1c5","branch":"HEAD"},"phet-core":{"sha":"e9f36af1","branch":"HEAD"},"phetcommon":{"sha":"0e4754fe","branch":"HEAD"},"scenery":{"sha":"2edf8a01","branch":"HEAD"},"scenery-phet":{"sha":"88ade507","branch":"HEAD"},"sherpa":{"sha":"1759eade","branch":"HEAD"},"sun":{"sha":"b66398a5","branch":"HEAD"},"tandem":{"sha":"c54f1082","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Able to reproduce myself with OSX FF 41.02.  The text dimming can also occur if the pointer is dragged across the photon emitter control panel.

This seems like a Scenery issue, so I will document an issue there.

@ariel-phet, I am not sure if this is severe enough to block the redeploy.  Could you please take a look at @phet-steele's capture of the issue and determine if this needs to be resolved before the RC can be deployed?  (https://drive.google.com/file/d/0B3HJopSo_QqLRFplUnVzTVA1Wlk/view?usp=sharing)

**Comment by ariel-phet** [comment]
I believe this is just a text rendering bug with FF, and certainly not sim specific. Not a blocking issue, and you have noted an issue in scenery. Closing.
