### ISSUE TITLE
Remaining redeploy items

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/molecules-and-light#127]
**Design/Admin**
- [x] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
Self assigning to check off once we have seen some working translations

**Comment by jessegreenberg** [comment]
molecules-and-light version 1.1.0 has been published and redeployed.

**Comment by ariel-phet** [comment]
The primer projects are being covered by https://github.com/phetsims/tasks/issues/429 and https://github.com/phetsims/tasks/issues/430 closing
