### ISSUE TITLE
.eslintcache is checked in

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/molecules-and-light#128]
I noticed that build server continually has errors with molecules-and-light and no other sims, and started to investigate.

I think the problem is caused by the fact the .eslintcache is checked into github for this sim. It results in working changes always ending up in the MAL repo on the server, and therefore a build fail because the command git pull fails because of working changes.

This will need to be removed and republished to work correctly with build-server.

**Comment by aaronsamuel137** [comment]
You can probably just remove it from the branch (and master) and run grunt deploy-production again. I don't think it needs a new maintainance release, you can just overwrite what is on the server.

**Comment by jessegreenberg** [comment]
Thanks for catching this @aaronsamuel137.

>You can probably just remove it from the branch (and master) and run grunt deploy-production again.

That was my hope as well, and that is what I did.  The .eslintcache files have been removed.  Must have mistakenly checked them in some how, but .eslintcache is correctly in my .gitignore file.  ```grunt deploy-production``` ran cleanly.  @aaronsamuel137 is there anything else left to do to verify that molecules-and-light is playing nice with build-server?

**Comment by aaronsamuel137** [comment]
I took a look in the log files and everything looked good. The sim redeployed and there were no working changes left in the MAL directory, which is what caused the problem before. I think this is fixed, but I'll reopen if I see anymore build fail emails.
