### ISSUE TITLE
Edge 25 molecule selection boxes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecules-and-light#132]
@ariel-phet @jonathanolson @jessegreenberg I feel like this is already a known issue, but might as well address it with phetsims/tasks/issues/523. There are obvious boxes around each molecule selection in Edge 25:

![mollightboxes](https://cloud.githubusercontent.com/assets/5863899/13265628/319a213e-da31-11e5-9a89-bdee1ff34511.PNG)

**Comment by ariel-phet** [comment]
@jonathanolson unless this a ~1 minute fix, I don't think it is worth it currently.

**Comment by ariel-phet** [comment]
If not a quick fix, please mark as priority:deferred and unassign

**Comment by jonathanolson** [comment]
No quick fix identified, could be from anti-aliasing (light behind dark), or something related to the deselectedStroke that isn't specified (defaults to brighter than black).

**Comment by jessegreenberg** [comment]
deselectedLineWidth of 0 is still visible on edge.  Setting the deselected stroke to black fixes this issue.

```js
      deselectedStroke: 'black',
      deselectedLineWidth: 0,
```

This issue can be closed, but will create a scenery issue to note that line widths in general seem thicker with Edge.
