### ISSUE TITLE
spectrumWindow.closeButton implementation for phet-io instance proxies

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecules-and-light#133]
In the below:
![m lbuttons](https://cloud.githubusercontent.com/assets/5863899/13444137/cb29c51c-dfc1-11e5-92b1-06a336d6752f.PNG)
Firing spectrumWindow.closeButton does nothing to the spectrumWindow.showProperty value. @jessegreenberg informed me this is because the "Close" button essentially does nothing, and the sim instead uses an input from anywhere on the screen to close the spectrum window.

Should be fixed for phet-io, assigning to @samreid for his two-cents. For phetsims/tasks/issues/532

**Comment by jessegreenberg** [comment]
Looks like the listener will need to be defined for PhET-iO and accessibility.  Added in commit above.  I am unable to test to verify that this is working in the wrapper, but pinging @phet-steele and @samreid to let them know that this was done.  Closing.

**Comment by samreid** [comment]
I'll reopen assigned to me to test in the wrapper, thanks @jessegreenberg.

**Comment by samreid** [comment]
Firing the close button from the instance proxies wrapper now properly closes the spectrum window, thanks @jessegreenberg.
