### ISSUE TITLE
Spectrum dialog doesn't reappear after closing once

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/molecules-and-light#148]
Keyboard navigation breaks the dialog's ability to reappear if the keyboard is used to close the dialog. Normal mouse behavior seems to persist until we close the dialog as above.

**Comment by jessegreenberg** [comment]
@mbarlow12 and I investigated this - @mbarlow12 discovered that it is because the close button listener doesn't is calling ```Dialog.prototype.hide instead``` of ```dialog.hide``` (in the local scope). Replacing should fix this issue.
