### ISSUE TITLE
Focus moves to EmissionRateControlSlider when it shouldn't

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#150]
For #143, I found a bug where focus can move to the slider on the photon emitter when it shouldn't.  Steps to reproduce:

- Break NO2 apart with an ultraviolet photon
- Change molecules

Focus will incorrectly go to the slider.

@mbarlow12 can you please investigate?

**Comment by mbarlow12** [comment]
We were unconditionally moving focus to the slider whenever the button's visibility changed. I moved the focus reset to the button listener and reverted the button's opacity changes back to simply setting the node's visible property.

See commit a8f0047.
