### ISSUE TITLE
Remove  explicit focusability handling for invisible UI elements

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#156]
In https://github.com/phetsims/scenery/issues/669, we made it so that  invisible items are hidden from keyboard navigation and screen readers. @mbarlow12 could you please remove the code that makes the "return molecule" button out of the focus order and verify that scenery is doing this for us?

**Comment by mbarlow12** [comment]
Confirmed that scenery properly removes the focus order. Closing.
