### ISSUE TITLE
ExcitationStrategy broken

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#158]
Found on master, NO2 doesn't 'light up' when it absorbs visible light.

**Comment by jessegreenberg** [comment]
@mbarlow12 would you mind looking into this?  I am wondering if this is from #144?  I can't find a reference to  ```highElectronicEnergyState.set()``` outside of ```fromStateObject``` so maybe it got removed.

**Comment by jessegreenberg** [comment]
Or maybe that Property was missed.

**Comment by mbarlow12** [comment]
Fixed in 4614bf8d715497641643f95674a287c323ef5786.
