### ISSUE TITLE
Add molecule state to the data stream for Mike Winters

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecules-and-light#159]
Mike emailed us after I delivered him a phetio dev version of MAL:

> Hi Michael,

>Thanks very much! It is working.

>After playing with it a little, I didn't see a property for the molecule state. I was hoping to find something like moleculeState = {"normal", "vibrating", "spinning"}. Is that information available? 

>I could imagine using the photon positions to infer if something was happening, but that seems less than ideal. Let me know if that is what I should do.

>Best,
Mike

I'll look into this, perhaps it would be easy to add.

**Comment by jessegreenberg** [comment]
Very possibly related to #151 and #154.

**Comment by zepumph** [comment]
Mike emailed back and wondered why these properties have to be nested under the Molecule name.

The following is a slack chat between @samreid and me.

Sam Reid [7:39] :
What if winters uses a matching pattern to detect which property to attach to?

Like a regular expression that matches `moleculesAndLight.moleculesAndLightScreen.model.*.vibratingProperty`


Michael Kauzmann [7:40 AM] 
that seems nice to me. I would only want to change it if we (the "designers" Michael and Sam) thought that it may be better to keep these on a single molecule tandem. Because to me it seems like that is a possibility. (edited)


Sam Reid [7:44 AM] 
Maybe that would actually be best.  The model can only have one molecule at a time right?


[7:44] 
So it would just be model.molecule


[7:44] 
and it could have a type: ‘CO’ or something like that


Michael Kauzmann [7:48 AM] 
It has an observable array of "Active Molecules" which keeps track of molecules (like when things break apart)


[7:49] 
But otherwise I only see `this.activeMolecules` being used as an array (as opposed to just a single molecule) when the breakApartEmitter fires and constituent molecules are added. (edited)

**Comment by zepumph** [comment]
I'm still unsure about how to handle this. I'll ask Mike if he can cover it with regex for now.

**Comment by zepumph** [comment]
MIke said he is good on a workaround. No matter I am interested in what would be best as a designed experience to a data stream user. @samreid should we just assume that when we get to MAL, there will be a data stream design meeting, and this will be sorted out?

**Comment by samreid** [comment]
A MAL PhET-iO design meeting sounds like a good plan.

**Comment by zepumph** [comment]
Alright then in that case I will go ahead and close this issue. From here I will try to work with Mike to get him usable phet-io features at the lowest cost to us (if it's small). Closing
