### ISSUE TITLE
Keyboard Navigation Dialog

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecules-and-light#160]
@terracoda I imagine this dialog will match the Ohm's Law/Resistance in a Wire dialogs, correct? I believe the molecule and light source selections act as radio buttons, so they won't need any explicit instruction in the dialog. Can you confirm?

Here's the latest dev:
http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.4.0-dev.1/molecules-and-light_en.html?accessibility

**Comment by terracoda** [comment]
@arouinfar,in the keyboard navigation meeting today, we decided to add some group details to the General Navigation section.

And we changed the two-way slider representation for all two-way sliders.

I will add the content here or in the design document and then assign to you.

**Comment by terracoda** [comment]
@arouinfar, how's this for content?

**Comment by terracoda** [comment]
oops, hit control enter...

**Keyboard Shortcuts**
**Light Source Frequency Slider**
Move slider: [Left Right] or [Up Down]
Move in smaller steps: [Shift] + [Left Right]  or [Shift] + [Up Down] (stacked)

**General Navigation**
Move to next item or next group of items: [Tab]
Move to previous item or previous group of items: [Shift] + [Tab] 
Move between group items: [Left Right] or [Up Down]
Exit this dialog: [Esc]

**Comment by terracoda** [comment]
@arouinfar, not sure we need both "Frequency" and "Slider". The verb "adjust" works better with "frequency" and "move" works better with "slider".

Any thoughts?

**Comment by arouinfar** [comment]
Thanks @terracoda! I think "Light Source Slider" is descriptive enough. "Frequency" may lead some users to believe that they are changing the frequency of the light, rather than the rate at which the photons are emitted. I'll mock up the dialog this afternoon.

**Comment by terracoda** [comment]
Awesome. I like "Light Source Slider", too.

**Comment by arouinfar** [comment]
@terracoda did you deliberately decide to leave out the pg up/pg down and home/end shortcuts?

**Comment by jessegreenberg** [comment]
Is there a reason that the slider in any sim needs custom content?  \I am also curious about 
 https://github.com/phetsims/molecules-and-light/issues/160#issuecomment-335932290 and why "Light Source Slider" needs to be used instead of "Slider Controls".  If we can use the same content as RIAW and ohms-law for all sliders that would make this dialog more scalable.

**Comment by arouinfar** [comment]
@jessegreenberg I would be fine with leaving it as "Slider Controls". @terracoda can you take a look at the two previous comments, and let me know how I should proceed?

**Comment by terracoda** [comment]
@arouinfar, sorry, I forgot the other shortcuts (it is such a small slider). I can add them.

@jessegreenberg and @jessegreenberg , I think that we need some flexibility in the naming of the controls, because so many sliders in PhET sims do not immediately look like sliders.

In the case of this sim there is only one slider, so I would not choose to say "Slider Controls" in the plural. I would like to just say "Light Source", but I thought that the more explicit "Light Source Slider" works here because the item looks like a slider. 

In John Travoltage, we just refer to the hand and foot, though under the hood they are sliders.

Do you agree that we need some flexibility here?

**Comment by terracoda** [comment]
Actually using the heading **Light Source Slider** makes it easier to just refer to slider below when describing the control.

How is a user to know that the button-thing on the Light Source is a Slider Control?

**Comment by terracoda** [comment]
**Keyboard Shortcuts**
**Light Source Slider**
Move slider: [Left Right] or [Up Down]
Move in smaller steps: [Shift] + [Left Right]  or [Shift] + [Up Down] (stacked)
Move in larger steps: [Pg Up] [Pd Down]
Move to start: [Home]

**General Navigation**
Move to next item or next group of items: [Tab]
Move to previous item or previous group of items: [Shift] + [Tab] 
Move between group items: [Left Right] or [Up Down]
Exit this dialog: [Esc]

**Comment by jessegreenberg** [comment]
Understood, thanks @terracoda, for sims like john-travoltage I can see us needing flexibility.

> How is a user to know that the button-thing on the Light Source is a Slider Control?

In this sim, it looks just like a normal slider so custom content doesn't seem necessary to me.

**Comment by terracoda** [comment]
@jessegreenberg, I agree it looks like a slider, but I still think it is better to match the dialog content to something that might actually eventually be in the parallel DOM content. In Ohm's Law, there is heading in the PDOM that matches "Slider Controls", but I do no think that will be the case here. 

My feeling is that the presence of the words "Light Source" somewhere in the dialog would benefit users.

**Comment by arouinfar** [comment]
Thanks for the clarification @terracoda! 

These controls sound a little odd to me:
> Move to minimum light source: [Home]
Move to maximum light source: [End]

The slider is controlling the rate of photon emission. Home turns off the light source, and End maximizes the rate. If we'd like to keep the "Move" language, then I think "Move to minimum value" and "Move to maximum value" makes a bit more sense. An alternative option would be:

Turn of light source: [Home]
Maximize rate of photon emission: [End] 

Here's a mockup with the usual slider shortcuts, but customized "Light Source Slider" heading.
![image](https://user-images.githubusercontent.com/8419308/31637883-0204a124-b28e-11e7-9bb1-2af2f33e4edf.png)

**Comment by terracoda** [comment]
@arouinfar, I also think "Move to min/max light source" is odd, and I think "Move to min/max value" is a little vague.In general, I feel increase and decrease would be better verbs than move for this sim.

Consistency is important, but so is clarity. We'll have to consider when a sim's control needs a bit more specific language. Hopefully, we will recognize a few patterns, so we don't have to use custom sim language for every sim.


It seems that in some cases "move" works fine to describe the sliders, and in some cases, it's better to focus on the fact that values of some kind are increasing and decreasing.

**Comment by terracoda** [comment]
@arouinfar, the general navigation text is not quite accurate. The Tab key will take a user to a group. A group basically behaves the same as an interactive item. Once on a group, and only once on a group will the arrow keys work to navigate between items in that group.

What do you think of this wording change? I think it has to be clear that un-grouped single items and groups are navigated as top-level navigable things and that items within a group use a sub-navigation technique.

**General Navigation**
Move to next item or next group: [Tab]
Move to previous item or previous group: [Shift] + [Tab]
Move between items in a group: [Left Right] or [Up Down]
Exit this dialog: [Esc]

I am ok with briefer language, but what is currently in the mock-up does not make sense to me.

**Comment by terracoda** [comment]
@arouinfar, here's my stab at the Light Source Sliders. If we make the heading more clear, maybe we can use briefer language in the description of the controls.

**Adjust Photon Emission Rate with Light Source Slider**
Adjust slider: [Left Right] or [Up Down]
Adjust in smaller steps: [Shift] + [Left Right] or [Shift] + [Up Down] (stacked)
Adjust in larger steps: [Pg Up] [Pd Down]
Turn off light source: [Home]
Maximize photon emission rate: [End]

"Set photon emission rate to maximum: [End]" is another option, but it is a bit longer.

I'm wondering if we will need a set of verbs for sliders. Something like "move", "adjust", "change", and possibly even "increase/ decrease". The context of the sim's interaction will likely dictate which verb is chosen.

"Adjust" would work for OL and RIAW, but there, we opted for the simpler verb, "move", in that case. Let's discuss that further in a meeting. For now, what do you of the text above?

**Comment by arouinfar** [comment]
In the 10/17/17 keyboard nav meeting, we decided to change the general wording for sliders that look like sliders:
* Adjust slider [left][right] or [up][down]
* Adjust in smaller steps: [Shift] + [left][right] or [Shift] + [up][down] (on two lines)
* Adjust in larger steps: [Pg Up][Pg Down]
* Jump to minimum: [Home]
* Jump to maximum: [End]

We also decided on the following terminology for the General Navigation section for sims with groups:
* Move to next item or group: [Tab]
* Move to previous item or group: [Shift] + [Tab]
* Move between items in a group: [left][right] or [up][down]
* Exit a dialog: [Esc]

Here's an updated mockup of the dialog.
![screen shot 2017-10-17 at 11 12 33 am](https://user-images.githubusercontent.com/8419308/31678966-ee5e2628-b32c-11e7-93a6-8d90eddd502c.png)

@terracoda can you take a look?

**Comment by terracoda** [comment]
@arouinfar, looks awesome!

**Comment by arouinfar** [comment]
Thanks @terracoda! Off to @jessegreenberg for implementation or reassignment.

**Comment by jessegreenberg** [comment]
@mbarlow12 would you mind working on this since you are taking lead for keyboard nav of this sim? You should be able to build this content with common view types in scenery-phet `SliderControlsHelpContent` and `GeneralNavigationHelpContent`, but let me know if the types are insufficient.

**Comment by zepumph** [comment]
@mbarlow12 it would be really nice to get you on board with https://github.com/phetsims/scenery-phet/issues/343 before/while implementing this dialog. Please note in that issue if you have any ideas to make these icons more consistently sized/shaped.

**Comment by zepumph** [comment]
I'll take a stab at this now that phetsims/scenery-phet#343 is solved for the most part.

**Comment by zepumph** [comment]
This is pushed to master. Back to @jessegreenberg for review.

**Comment by zepumph** [comment]
@jessegreenberg when you review this, could you especially look at the string key I made, I'm not sure if we want a convention for this, but adding "KeyboardHelp." like prefix may be something we want to do before publishing all of these scenery strings.

From slack:
hey in scenery-phet-strings_en.json, do you think that all of the keyboard help strings should be "KeyboardHelpDialog.X" or "KeyboardHelpContent.X" for consistency?

**Comment by jessegreenberg** [comment]
Code changes look great @zepumph.  I think that would be an improvement  to the keys. Ill udpate the ones in scenery-phet. This needs to be done along with https://github.com/phetsims/QA/issues/66. Dialog looks great to me! @terracoda or @arouinfar can you check master and review the look before we close this isssue?

**Comment by arouinfar** [comment]
Looking pretty good @zepumph @jessegreenberg! I've noticed a few changes from earlier designs (such as the latest rc of RIAW). Notably, the arrow icons are much larger than before and there appears to be a bit less padding in the string-containing keys, such as "Shift". The end result is that the keys look a bit more crowded, so I think the RIAW look is preferable.

RIAW:
![image](https://user-images.githubusercontent.com/8419308/32909883-075c99d4-cac5-11e7-974b-9ec31a111f34.png)

MAL:
![image](https://user-images.githubusercontent.com/8419308/32909894-10cc24ee-cac5-11e7-88d7-3b67f99292ba.png)

**Comment by jessegreenberg** [comment]
Thanks for pointing this out @arouinfar.  As part of the review in phetsims/scenery-phet#343 Ill test the options to make them match the mockup the RIAW dialog.

**Comment by zepumph** [comment]
Thanks @jessegreenberg. The arrow keys should be easy. I think that I decreased the width padding because of the look of the square keys, so make sure to test with the KeyNode component view in the scenery-phet demo to make sure that both types of keys continue to live in harmony. We may need to add another option/create a different key type. Keep me posted if I can help. 

This will be a good test of the option efficacy.

**Comment by jessegreenberg** [comment]
Here is the dialog for MAL now:
![capture6](https://user-images.githubusercontent.com/6396244/32921148-ad1cd68a-cae9-11e7-80d0-5bed6134e675.PNG)

@arouinfar can you please review the look now?

**Comment by arouinfar** [comment]
Looks wonderful @jessegreenberg!

**Comment by zepumph** [comment]
@jessegreenberg ready to close?

**Comment by terracoda** [comment]
I agree looks awesome!

**Comment by jessegreenberg** [comment]
Indeed, thanks for implementing this @zepumph, ready to go.
