### ISSUE TITLE
branch: description

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#170]
In support of #169, this branch has prototype description for this sim. Would be great a s a one-off deploy, though that has not been implemented yet. But presumably could be used with this branch.

In the meantime I will update version and package.json in this branch to reflect the way the process will work.
branch: sonification
version: 1.5.0-sonification.1
deploys to molecules-and-light/1.5-sonification.x

**Comment by jessegreenberg** [comment]
@mbarlow12 are you working in this branch at all? I *think* that this branch can be deleted since more recent description work is happening in #181, is that correct?

**Comment by ariel-phet** [comment]
@jessegreenberg I think OK to create this branch considering current status of various people who have worked on it.

**Comment by jessegreenberg** [comment]
Here are the commits currently on `description`
```
$ git log master..description
commit 023f69a8ea6b3565771bad4aeca8a59be5145a25 (origin/description, description)
Author: Jesse Greenberg <jesse.greenberg@colorado.edu>
Date:   Mon Jan 22 11:29:37 2018 -0700

    update version id name to  reflect one off,  see #169 and #170

commit b3720035ce1471bc9a455f1787df5922ef528ce8
Author: Jesse Greenberg <jesse.greenberg@colorado.edu>
Date:   Mon Jan 22 11:24:42 2018 -0700

    screen label for #169

commit 45c967eab8e34ec3b34c69873ba6150382bfe071
Author: Jesse Greenberg <jesse.greenberg@colorado.edu>
Date:   Mon Jan 22 11:20:30 2018 -0700

    play area descriptions for #169

commit df2b3d951d3630b7c34b3431ced2f4e5e7db03d6
Author: Jesse Greenberg <jesse.greenberg@colorado.edu>
Date:   Mon Jan 22 11:07:40 2018 -0700

    summary node is first in navigation order, see #169

commit 3a59452c48933ac51e4ffedf467320f0996c9abf
Author: Jesse Greenberg <jesse.greenberg@colorado.edu>
Date:   Mon Jan 22 11:06:20 2018 -0700

    finish scene summary for #169

commit e7a68f4576fdb6207810e53c74574b187d745089
Author: Jesse Greenberg <jesse.greenberg@colorado.edu>
Date:   Mon Jan 22 11:03:13 2018 -0700

    initial commit for #169
```

**Comment by jessegreenberg** [comment]
Descriptions in this branch are actually not as up to date as master so this branch can be deleted.

**Comment by jessegreenberg** [comment]
Deleted.

**Comment by jessegreenberg** [comment]
Re-deleted as part of https://github.com/phetsims/special-ops/issues/198
