### ISSUE TITLE
User question: Water/UV Light behavior

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molecules-and-light#178]
> Problem description: I noticed that when you go to Water and test UV Light that nothing happens. It's well documented that UV light causes the dissociation of water and for those teachers using this simulation to teach about greenhouse gasses and the consequences of the ozone hole it would be helpful if this simulation showed that water will dissociate under UV light which is one of many reasons the ozone layer is so incredibly important. Venus, for example, used to have much higher percentages of water in it's atmosphere but because of the dissociation of water under UV light it's water has been lost, converted to H2 that escaped into space and O that combined with other atoms which explains why Venus has so many oxides. At this point I am simply explaining that the simulation is incomplete and that not every interaction is included in this simulation but is simply a good starting point to get us talking about the different kinds of interactions light can have with atmospheric gasses, so it's not a huge problem but it would be a helpful addition to this simulation if you have the time to do so. Thank you :)

**Comment by arouinfar** [comment]
@oliver-phet from the Teacher Tips:

> Each photon represents a range of energy, but not all absorptions in that range are shown. Some examples of what is not included: CO2, H2O, NO2 and O3 all have stretch vibrational modes in the IR, O3 absorbs weakly in the visible, and absorption of visible light by NO2 is dissociative at some wavelengths (blue or violet). The UV photon comes from the UV-B region (290-320 nm), which is the range absorbed by the earth's ozone layer; at shorter wavelengths the other molecules also
absorb UV. 

I did a bit of searching, and it seems that water does not dissociate in the specific UV-B region included in the sim. In general, the [primary photodissociation reactions](https://en.wikipedia.org/wiki/Photodissociation#Photolysis_in_the_atmosphere) in the atmosphere are considered to be the dissociation of ozone and nitrogen dioxide, both of which are included in the sim.

**Comment by oliver-phet** [comment]
Thanks, @arouinfar. Responding to user and closing.
