### ISSUE TITLE
startup crash due to custom close button in SpectrumWindowDialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#184]
Reported by @zepumph.

After the Dialog close button was made mandatory in https://github.com/phetsims/joist/issues/413, MAL started crashing on startup with PhET-iO enabled.  E.g.

http://localhost/~cmalley/GitHub/molecules-and-light/molecules-and-light_en.html?brand=phet-io&ea&phetioStandalone

Stack trace was complaining about the tandem id for the close button being registered twice in `SpectrumWindowDialog`.   Here's the trace:

```
Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.view.spectrumWindowDialog.closeButton.pressListener
assert.js:22:13
window.assertions.assertFunction<
http://localhost/assert/js/assert.js:22:13
addInstance
http://localhost/phet-io/js/phetio.js:577:19
addInstance
http://localhost/phet-io/js/phetio.js:670:7
addInstance
http://localhost/tandem/js/Tandem.js:134:13
initializePhetioObject
http://localhost/tandem/js/PhetioObject.js:147:7
PhetioObject
http://localhost/tandem/js/PhetioObject.js:75:7
PressListener
http://localhost/scenery/js/listeners/PressListener.js:115:5
createListener
http://localhost/sun/js/buttons/ButtonModel.js:106:14
RectangularButtonView
http://localhost/sun/js/buttons/RectangularButtonView.js:99:25
RectangularPushButton
http://localhost/sun/js/buttons/RectangularPushButton.js:51:5
Dialog
http://localhost/sun/js/Dialog.js:152:23
SpectrumWindowDialog
http://localhost/molecules-and-light/js/moleculesandlight/view/SpectrumWindowDialog.js:58:5
```

The problem is that `SpectrumWindowDialog` is creating its own custom close button, and adding it as part of the Dialog content.   So the custom and standard close buttons attempt to use the same phetioID.

The solution is to delete the custom close button.

**Comment by zepumph** [comment]
Looks good, thanks @pixelzoom.
