### ISSUE TITLE
slider focusHighlight is "stuck"

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecules-and-light#190]
The focus highlight doesn't move with the slider right now, this should block publication on all a11y related releases of this, here is a screen shot.

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/50622807-a700d180-0ebc-11e9-895a-6cabca4aa645.png)

**Comment by jessegreenberg** [comment]
Thanks @zepumph, would be good to investigate this since it may not be a sim specific issue.

**Comment by jessegreenberg** [comment]
It looks like this used to be working because the thumb itself with a pink rectangle child was the focus highlight for the slider. But that has changed, and the focus highlight is now just set on the slider. But that change used FocusHighlightPath, which doesn't track the node's transform.

**Comment by jessegreenberg** [comment]
Accessibility improvements since this sim was last worked on means that we don't need to create a custom highlight for the thumb, the default highlight in Slider will go around the custom thumb's bounds.

**Comment by zepumph** [comment]
Before the focusHighlight was touching the background, now there is a bit of space:

![image](https://user-images.githubusercontent.com/6856943/50939298-aae6a380-1428-11e9-8206-581d8766ea85.png)


Does this matter to you @jessegreenberg?

**Comment by jessegreenberg** [comment]
Thank you @zepumph, we scoured the related issue and couldn't find explicit documentation about it, but after sleeping on it I am remembering that having the highlight hug the grey box makes it easier to see against the red of the emitter node. Ill make the change, and add documentation to the code about why the smaller highlight was required.

**Comment by jessegreenberg** [comment]
Here it is now, @zepumph does this look better?
![capture](https://user-images.githubusercontent.com/6396244/50986270-63b5ec80-14d4-11e9-9417-d6918ab745c8.PNG)
