### ISSUE TITLE
Fill in empty H1 element

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#194]
I was just reviewing some of our accessible sims, and I noticed that the PDOM for Molecules and Light has an empty H1 element.

It doesn't seem to me that there would be any harm and potentially significant benefit of filling the empty H1 with the title of the sim, like so:

```html
<h1 tabindex="-1" id="label-292-355">Molecules and Light</h1>
```

Tagging @jessegreenberg, @emily-phet and @terracoda for discussing at our next meeting.

**Comment by terracoda** [comment]
Actually since this sim not on anyone's plate at the moment. I'll just mark it for Friday's a11y meeting.

**Comment by jessegreenberg** [comment]
Interactive descriptions are being designed and worked on now, this will be cleaned up as part of that. Closing.
