### ISSUE TITLE
User request: UV light on diatomic oxygen

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molecules-and-light#197]
Received from sim suggestion google form:
> The sim shows no effect when UV light shines on diatomic oxygen, though we know it is UV that induces cleavage in the oxygen-oxygen bond, allowing ozone production. It would be cool if the simulation could reflect that.

**Comment by arouinfar** [comment]
@oliver-phet O2 photodissociates in the UVC region, while the UV band represented in the simulation is UVB. In general, this simulation is more qualitative, and does not represent every possible absorption process. The Teacher Tips have quite a bit of information about the model simplifications that this user may find useful.

**Comment by oliver-phet** [comment]
Thanks, @arouinfar. Email to user sent! Closing for now.
