### ISSUE TITLE
Panning with "middle" click (wheel) isn't supported

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#204]
For https://github.com/phetsims/QA/issues/419
Found on Win 10 Chrome with Mouse
From issue:
>Mouse Control:
>'Ctrl' + 'mouse wheel' to zoom in and out (Windows)
>'Cmd' + 'mouse wheel' to zoom in and out (macOS)
>'mouse wheel' to pan around screen

The panning only works if panning up or down.  This is fairly expected on its face, but clicking down on the wheel does not allow for 8-directional scrolling, and there is no scroll bar to scroll right and left.  Arrow keys on keyboard do allow this type of scrolling.

Not sure if any of this can be worked around.  It seems off to me, but if it is expected/unavoidable, please feel free to close.

**Comment by jessegreenberg** [comment]
Interesting, thanks for pointing out @KatieWoe it would be really cool to support this. Panning to the left and right *does* work with a wheel that supports left and right movement. But specifically what doesn't work is pressing down on the wheel to create a cursor like this:
![image](https://user-images.githubusercontent.com/6396244/63959763-ea670c00-ca5a-11e9-9e79-058a524459fe.png)
To pan in all directions.

**Comment by jessegreenberg** [comment]
Supported with the above commit.

**Comment by KatieWoe** [comment]
Supported, but seems to behave a bit differently then i would expect.  The icon for the cursor look like the one for dragging an object rather than panning.  It also doesn't continue to work after you let go.  If all of this is intended then that's fine.

**Comment by jessegreenberg** [comment]
> It also doesn't continue to work after you let go

Got it, thanks. Ill fix that.

> The icon for the cursor look like the one for dragging an object rather than panning.

The cursor I used was the closest one I could find that is supported by CSS cursors. If we want something more custom we will have to do extra work to support that. At this time, I don't really think it is worthwhile. But Ill check in with @emily-phet and @terracoda.

**Comment by jessegreenberg** [comment]
@KatieWoe can you please see if the middle mouse button behaves better after the above commit in this version? Does middle mouse panning also *stop* when you expect it to now?

https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-customZoom.13/phet/molecules-and-light_en_phet.html

**Comment by KatieWoe** [comment]
Looks good @jessegreenberg

**Comment by jessegreenberg** [comment]
Alright! Thank you!
