### ISSUE TITLE
Scrolling around dialog box

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#207]
For https://github.com/phetsims/QA/issues/419.  Win 10 Chrome (touch screen).
When zoomed in and looking at a dialog box, it can be slightly difficult to pan when using a touch screen.  If you try to start the pan outside the box, it registers it as a click to leave the dialog.  Not necessarily a major problem, and I'm not sure if there is a clean solution.

Video:
https://drive.google.com/file/d/1GkCKlxfkUrahFo7VzGZkpWSYhvOj2JDI/view?usp=sharing

**Comment by jessegreenberg** [comment]
Thanks for pointing out @KatieWoe, I think we can improve this.

**Comment by jessegreenberg** [comment]
This is the same issue as not being able to pan out of a clickable item when it takes up much of the screen. Currently, if any pointer is "attached" (meaning that it is marked as responsible for firing a listener) we don't allow panning.

If you go to  another example for web content like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio and zoom way in to the radio button example then try to scroll by pressing down on a radio button, it does allow you to do it. That makes sense to me. I think we should strive for that behavior.

**Comment by jessegreenberg** [comment]
The above is a potential solution for this. It supports panning everywhere by interrupting input if movement occurs while the pointer is down. It also supports a way to prevent this when we need (like for draggable things). So far it is working pretty well, though I am not sure if this is the best solution.

It presented a different issue though, which is that interrupting pressed buttons continues to fire them.

**Comment by KatieWoe** [comment]
Seems to be behaving better now.

**Comment by jessegreenberg** [comment]
Excellent, thanks
