### ISSUE TITLE
Long String Test causes some Pointer Area overlap

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/molecules-and-light#210]
**Test device**
Windows 7 Laptop
**Operating System**
Professional 6.1
**Browser**
Chrome version 77.0.3865.75 
**Problem description**

When using the long string test the show light spectrum button moves close enough to the pause button that their pointer areas overlap.
**Steps to reproduce**
1. Enter the query ?showPointerAreas&stringTest=long
**Visuals**
![2019-9-11PntArelngMlclght](https://user-images.githubusercontent.com/54685448/64737351-dafbb000-d4a9-11e9-804d-38e66220df8c.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-customZoom.7/phet/molecules-and-light_en_phet.html?a11y&showPointerAreas&stringTest=
Version: 1.5.0-customZoom.7 2019-08-28 23:16:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
Language: en-US
Window: 1366x576
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
This is no longer an issue now that the UI has been changed to include TimeControlNode
![image](https://user-images.githubusercontent.com/6396244/89817633-82e48800-db16-11ea-9b8c-33d9351d5388.png)
