### ISSUE TITLE
Zooming difficulties with a small screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#212]
For https://github.com/phetsims/QA/issues/419. IOS 12.4 on an iPhone 7
When zooming in on a small screen such as an iPhone, I noticed two potential problems.
1. If you zoom in on the list and it takes up the whole screen, scrolling can be hard.
2. If the first finger down hits a button such as the one to look at the light spectrum, attempting to zoom activates the button instead.  I had this happen by accident several times.

https://drive.google.com/file/d/1kiakHJ7cNO1Z3zASHCFtk74nrMaHnx-Q/view?usp=sharing

**Comment by KatieWoe** [comment]
Looks good

**Comment by jessegreenberg** [comment]
Great, thank you @KatieWoe
