### ISSUE TITLE
Photon Emitter radio buttons aren't working in IE11 (published version)

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#222]
In #211 @KatieWoe found out that the photon emitter radio buttons aren't working with keyboard navigation in IE11 in the published version. Molecule buttons work OK, and all are working in IE11 off of master. I expect that it will be 2-3 hours to debug on IE11 and then prepare a maintenance release for QA to spot check. @emily-phet do you think it is important to do this now? Alternatively, we could wait and pick up this fix naturally with the next publication of MAL.

**Comment by emily-phet** [comment]
I think we should hold off until the next publication - probably in the first quarter of 2020.

**Comment by jessegreenberg** [comment]
OK, thanks. Adding the "fixed-awating-deploy" label to indicate that this is fixed in master and we expect it to be fixed in the next publication.

**Comment by jessegreenberg** [comment]
Closing, since IE11 is no longer a platform we will test for sims.
