### ISSUE TITLE
Change "Light Source" h3 to "Light Sources" in PDOM 

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#227]
@Matthew-phet and I were testing MAL dev version 1.5.0-dev.18 https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.18/phet/molecules-and-light_en_phet.html?a11y

Please add an "s" to "Light Source" in H3 that names the radiobutton group for the four light sources. The help text is great!

This was an over sight on our part. There is no "s" in the design doc.

**Comment by jessegreenberg** [comment]
Thanks for pointing out, done in the above commit.
