### ISSUE TITLE
Long molecule responses: Shorten delay and repeat long response on every third response

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#228]
The current delay observed in [1.5.0-dev.18](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.18/phet/molecules-and-light_en_phet.html?supportsSound&a11y) does make it so we hear the longer molecule response at least once, most of the time.

After playing with the sim, @Matthew-phet and @terracoda think that a better approach might be to have a shorter delay (possibly even no delay) and then repeat the long version of the response on every third molecule reaction. 

There seems to be time and it seems a bit more interactive to us.
 
@jessegreenberg, is that kind of repeated pattern doable?
If so, please implement. If not, please provide your thoughts on the matter.

**Comment by jessegreenberg** [comment]
This is technically possible, but the delay was initially added to prevent a long queue up of alerts after the screen reader reads aria-valuetext/radio button responses, not to make sure they are always spoken. So if we do this we will still have that problem.

**Comment by jessegreenberg** [comment]
Im going to look at utteranceQueue and see if there is a better workaround that doesn't use a delay.

**Comment by jessegreenberg** [comment]
Delay removed for now in the above commit.

**Comment by jessegreenberg** [comment]
@terracoda @Matthew-phet here is a new version with this. Can you please try and see how alerts appear in this version and determine if any further work is necessary?

https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.19/phet/molecules-and-light_en_phet.html?a11y&supportsSound

**Comment by terracoda** [comment]
The alerts are all firing nicely with no delay on VoiceOver. 
VoiceOver stops announcing responses from time to time but that is a known bug and you just needs to restart VoiceOver to get them going again.

**Comment by terracoda** [comment]
I still think it may be beneficial to repeat longer responses occasionally. I think this would enhance the current experience. We can discuss at design meeting, though. 

As it is working right now (at least on my machine) the experience is nice enough for getting feedback from screen reader users.

**Comment by terracoda** [comment]
We have had feedback from at least 3 interview participants that the amount of description in the normal-speed responses is good.

There is no need to repeat the longer response at regular intervals.

Closing this issue.
