### ISSUE TITLE
Rarely hear break-apart response when molecule breaks apart

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#229]
When testing dev version [1.5.0-dev.18](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.18/phet/molecules-and-light_en_phet.html?supportsSound&a11y) 

we rarely heard the break-apart response. We did hear it on VoiceOver at least once, maybe twice, but we never hear it while using on NVDA.

When checking with A11y View, we noticed the response rarely fired, so maybe there is a bug in the code?

We would need this fixed before interviews.

**Comment by jessegreenberg** [comment]
This is happening because of the delay that we added before saying an alert. No other alerts happen here so we need to either remove the delay in general or remove it in this case. Will review other issues related to the delay before working on this.

**Comment by jessegreenberg** [comment]
The delay was removed and this is now fixed.
