### ISSUE TITLE
Design Interview Questions

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#231]
Interviews are coming up (Dec 18th and possibly 20th)

Please add any questions that should explored about the current design.

1. What to say, if anything, when photon passes through repeatedly?
2. Do the radiobutton interactions (Light Sources and Molecules) communicate that the changed selections are updating what is in the Observation Window? Is it obvious that this is what is happening? effectively?
3. Was it easy to find the Return Molecule button? Do have any thoughts on where the "Return Molecule" button should be placed? 
4. Where should focus go when the molecule is returned after a break-apart (after pressing the Return Molecule button). 
5. What do you think the "Next Frame" is for? What would you use it for? Walk through an example and get feedback on level of detail needed. Will try a Wizard of Oz format.

**Comment by BLFiedler** [comment]
I think we made some pretty big decisions w/r/t the static descriptions of the molecule geometry/bond nature. Do we want to inquire as to the clarity of that information and if it is appropriately layered? I think that is maybe secondary to the above questions though.

**Comment by emily-phet** [comment]
- (Something to consider, not necessarily asking explicitly) Does the basic organization of the static/dynamic descriptions make sense? Does the information provided in summary, in play area, etc. feel 'about right'). 
- (A key moment to attend to) How long does it take to make sense of all the sounds heard once the light source is turned on? What is the thought process taken to make sense of these?
- After playing with the sim, consider the sound design - were the sounds helpful, enjoyable, cohesive? Did any sounds stand out in good or bad ways? (looking forward to hearing how users describe the sim sounds!)

**Comment by arouinfar** [comment]
This piggybacks on @BLFiedler's comment a bit, but in terms of the learning goals, I'd want to know if the users are able to connect the molecule geometry/structure to the interaction with the light (eg. microwave photons induce rotations in asymmetric molecules).

**Comment by terracoda** [comment]
Based on interview feedback and design discussions many design changes have been made to MAL's interactions and MAL's interactive description:
1. Light Source slider replaced with Light Source button/switch
2. Sim Speeds for exploration at normal and slow speeds
3. Added Context Responses to support use of Pause/Play and Step Forward buttons
4. Improved wording for Context Responses that describe the photons and the molecule excitations (at all speeds: normal, slow and step forward)
5. Improved wording for Dynamic Descriptions of molecule phases in the Observation Window.

### What questions would you to ask to evaluate these design changes?
Please add your questions if you have any to [this document](https://docs.google.com/document/d/1ccHK-418NR4KnzXan1YkWTq81z5Ns9L5fPfS8bl0SfU/edit#).

**Comment by BLFiedler** [comment]
Notes in document!

**Comment by arouinfar** [comment]
@terracoda I read through the document, and I don't have anything to add. I like/agree with the points @BLFiedler added to the doc.

**Comment by terracoda** [comment]
@BLFiedler thanks for your suggestions. I've decided to do interviews instead of asynchronous review of MAL's design changes. I adapted @BLFiedler 's suggestions into what to watch for points and 6 questions.

See new [document template ](https://docs.google.com/document/d/1mvN6hZBnWOwG-j3ZsaMJAHZ_7V5W249idp57u3spXcY/edit)for zoom interviews.

**Comment by terracoda** [comment]
I'll close this issue for now. I think I am ready for MAL's final evaluations.
