### ISSUE TITLE
Has help text for radio groups been updated recently?

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#232]
@Matthew-phet , I just compared design doc with dev version 18, and I am not sure we have the updated help text implemented. Could you verify what our decision was. I think I forgot to make an issue for the change we discussed.

**Here's what in the sim:**
- For Light Sources: "Choose light source, ordered low to high energy, and observe effects on molecule."
- For Molecules: "Choose molecule and observe interactions with light source."

**Here's what in the design document:**
- For Light Sources: "Choose light source for observation window ordered low to high energy."
- For Molecules: "Choose molecule for observation window."

While, I like what is implemented, I think we decided to make it more obvious that changes to the radio buttons are changing what is in the Observation Window because there are currently no responses for radiobutton selections.

@Matthew-phet, can you confirm that the change needs to be made, and then assign to @jessegreenberg .

**Comment by jessegreenberg** [comment]
I recall that we decided to change these as well and I did not update the sim since that discussion. I saw in the design document that these were changed on Nov 26 (day after we talked about it) so Ill go ahead and update the sim.

**Comment by jessegreenberg** [comment]
Updated in the above commit to use the strings in the design doc and in https://github.com/phetsims/molecules-and-light/issues/232#issue-534248129. @terracoda @Matthew-phet this is pretty cut and dry so I am just going to close without further review.

**Comment by terracoda** [comment]
Thanks @jessegreenberg !
