### ISSUE TITLE
Wording for photon emitter aria-valuetext

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#234]
Currently, the aria-valuetext is something like
"Infrared photon emits quickly"

which is read every time the photon emitter slider is moved.

I have two thoughts about this wording.
1) The photon isn't emitting anything, the light source is emitting the photons. Would it be more correct to say "Infrared light source emits photons quickly"? Or "Infrared photons emitted quickly"?
2) I still wonder if this wording will make the user think we are referring to photon speed when this is really about photon emission rate. Would it be more correct to say something like "Infrared light source emits photon at a quick rate"? I know this is wordy, but just want to make sure that the current shorter version is not incorrect.

Just two considerations, if the current wording is indeed accurate, feel free to close.

**Comment by BLFiedler** [comment]
You could put the adverb on the verb instead: "Infrared Light Source quickly emits photons"

I agree the current text is confusing. From a content side I'm fine with the second, longer suggestion as well.

**Comment by terracoda** [comment]
Great question @jessegreenberg.
The stated values in the design doc should actaully be region ranges and not individual values.

That said, I don't think we have thought through this interaction very clearly.
This is actually quite tricky!
We have not thought through how the `aria-valuetext` will support the learner's interaction on focus and then again when they are adjusting the slider.

I think when the leaner lands on the slider, they need to know what light source is the currently selected and what the current emission rate is.

I like "Light Source" but could it be made dynamic?

@jessegreenberg is it possible to make the slider's label dynamic?
- {{Infrared}} Light Source
- {{Microwaver}} Light Source 
- {{Visible}} Light Source
- {{Ultraviolet}} Light Source

Then given the current 4 region rages, the slider could sound something like this on focus:
- Infrared Light Source, slider, off
- Infrared Light Source, slider, photon rate very slow
- Infrared Light Source, slider, photon rate slow
- Infrared Light Source, slider, photon rate fast

At a region change, would it possible to just say the changed rate?
- very slow
- slow
- fast 

If a dynamic label is possible, maybe better regions names would be slow, medium, fast? For example:
- Infrared Light Source, slider, off
- Infrared Light Source, slider, photon rate slow
- Infrared Light Source, slider, photon rate medium
- Infrared Light Source, slider, photon rate fast

**Comment by terracoda** [comment]
But, first question @jessegreenberg, is a dynamic label possible?

**Comment by jessegreenberg** [comment]
@BLFiedler I like "Infrared Light Source quickly emits photons".

@terracoda I also like "Infrared Light Source, slider, photon rate fast"

> is it possible to make the slider's label dynamic?

Yes it is, and would be a simple change.

> At a region change, would it possible to just say the changed rate?

We could set this as the aria-valuetext, but I don't think there is a guarantee that the screen reader won't also say other things. So it might end up as
"Infrared Light Source, very slow".

This sounds more complicated though, what are the benefits of changing the value-text like this?

**Comment by terracoda** [comment]
@jessegreenberg, I didn't finish out the examples. I am not sure I understand your concern, but we could also set the aria-valuetext to:
- photon rate slow
- photon rate medium
- photon rate fast

And then it only get read out at region changes. The regions are quite small in the case of this slider, so maybe everything will be perfect.

**Comment by jessegreenberg** [comment]
Ah I see - so it isn't shorter text when the region changes, but ONLY read any text when region changes. Hmm, I don't think that is generally how screen readers handle reporting of the changing slider value so I don't think that would be possible.

**Comment by terracoda** [comment]
Generally, if there is no change in value, nothing is read out.

**Comment by terracoda** [comment]
For keyboard we often have to jig things to avoid blank steps, and for mouse we have to adjust the utterance queue to prevent too many things from piling up.

It's a challenge. I am willing to try the 4 regions:
- photon rate off
- photon rate slow
- photon rate medium
- photon rate fast

**Comment by terracoda** [comment]
@BLFiedler and @Matthew-phet, for me it's important to think about the name of the slider, and any responses (object responses in this case) together with the help text for the interaction. I try to economize phrases in object responses and context responses by strategically placing certain key content words in any of the three places. So if the word "emit" can't go in the object response, maybe it can go in the help text.

I'm just putting all three here for reflection:
- Label if dynamic: {{Infrared}} + Light Source
- Interaction function/role name: slider
- Current help text for slider: Adjust to emit photons at different rates.

So, in the help text we have 3 key words: "emit", "photons", and "rates". And if we have a dynamic label "Infrared" will be read out on focus. 
 
Now, given that the help text is likely to be read at least once, what else does the learner need to know about the interaction when they adjust it?

Currently on focus (with VoiceOver) I hear:
- Infrared light source off, Light Source, slider.

Maybe we don't need to repeat "light source"?

**Comment by terracoda** [comment]
@jessegreenberg, I am hearing the label of the slider repeat often when an adjustment is made, but this doesn't happen on other sliders we have implemented. It doesn't happen in JT or GFL, for example.

There is something different about the Light Source slider.

**Comment by terracoda** [comment]
If the label was "Infrared Photon Rate" slider, words describing the actual rates might work perfectly on their own? Imagine as an example, does this work? Maybe not, maybe? These are potential object responses fired on focus:
- light source off, Infrared Photon Rate, slider
- very slow, Infrared Photon Rate, slider
- slow, Infrared Photon Rate, slider
- fast, Infrared Photon Rate, slider

**Comment by BLFiedler** [comment]
Ooohhhh. I do like that last suggestion @terracoda. I think there are multiple places for the user to be made aware there is a light source there, and if they're remind when it's off, I think calling that slider the {EM spectrum} Photon Rate is very informative and concise.

I think eventually you will learn enough physics, chemistry & math that you won't need Amy or me! 😆

**Comment by terracoda** [comment]
@BLFiedler, I think my suggestion of "Photon Rate" slider is a re-hash of something @arouinfar already pointed out to me when we first looked at this sim, so I am not yet ready to let go of yours and @arouinfar 's content knowledge ;-)

I do enjoy diving deep into the content and how best to present it in an interactive experience, though!

**Comment by jessegreenberg** [comment]
> I am hearing the label of the slider repeat often when an adjustment is made, but this doesn't happen on other sliders we have implemented. It doesn't happen in JT or GFL, for example.

Oh I see! OK I will make a new issue to investigate this.

OK it sounds like we have a consensus in https://github.com/phetsims/molecules-and-light/issues/234#issuecomment-564070461 I will implement that.

**Comment by terracoda** [comment]
@BLFiedler and I have consensus, and hopefully @Matthew-phet likes it too. I'll give him the heads up.
This change may require a couple of tweaks to the Screen Summary. I'll read through the Screen Summary and post a new issue for any updates.

**Comment by Matthew-phet** [comment]
Yup! This looks like a good change

**Comment by jessegreenberg** [comment]
Great! This is done in the above commit, @terracoda or @Matthew-phet can you please review>?

**Comment by terracoda** [comment]
@jessegreenberg, the dynamic Photon Rate slider and its 4 spedds sound awesome!
Thanks @jessegreenberg!
