### ISSUE TITLE
Remove extra help text above Pause/Play/Next Frame buttons

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#238]
@jessegreenberg, I think the phrase: "Pause what is happening in the Play Area" is old and was meant to be replaced by "Pause, play, or step forward in time while paused."

Could you please remove the first paragraph, preferably before interview on Dec 18th.

**Comment by jessegreenberg** [comment]
Done in the above commits:
![image](https://user-images.githubusercontent.com/6396244/70657582-17b28100-1c2a-11ea-8f96-2a5e674a6a00.png)

Back to @terracoda to review.

**Comment by terracoda** [comment]
@jessegreenberg, I am not seeing or this on master.

**Comment by terracoda** [comment]
@jessegreenberg, apologies help text is correctly no longer there. I am not seeing the "Step" button label yet.

That is likely separate.
