### ISSUE TITLE
Do not hear "disabled" on Next Frame button when it is visually greyed out

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#239]
@jessegreenberg, the Next Frame button is visually greyed out (visually disabled) when the Play button is not in its Paused state. 

With screen reader software, I don't hear anything about the button being disabled.

I am assuming there is an actual HTML5 `disabled` attribute on the button, and that it might not be communicating the `disabled` state.

Could you check? If there is an HTML5 attribute in the PDOM, could you try using `aria-disabled="true"` instead. The aria attribute might be better supported by screen reader software, though in an ideal world both should work the same.

If there is no disabled attribute at all, we can check if adding the HTML5 attribute will work before employing the aria attribute. I am not sure of how well supported the HTML5 attribute is today (2019).

I found this [blog post on aria-disabled](https://a11y-101.com/development/aria-disabled), but I do not know how recent it is.

**Comment by terracoda** [comment]
Ideally, it would be great to hear disabled on the Next Frame button before interview on Dec 18th.

**Comment by jessegreenberg** [comment]
It looks like this hadn't been added at all yet. I added `aria-disabled` as we have done with other buttons and check boxes. VoiceOver now reports "dimmed" when focus lands on the button. Back to @terracoda for review.

**Comment by terracoda** [comment]
VoiceOver is so visual sometimes... I guess "Next Frame dimmed button" when greyed-out and disabled sounds better than just "Next Frame button". 

Thanks @jessegreenberg.
I'll go ahead and close.
