### ISSUE TITLE
Still hear "Next Frame" button

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#241]
@jessegreenberg, I think we discussed this in the design doc, but I didn't make an issue for it.

I think, "Next Frame" is supposed to be "Step". 

Since I think you did this in common code, there might be an old string getting in the way in MAL's code??

I saw a screenshot you shared that had the correct label, but in https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.20/phet/molecules-and-light_en_phet.html?a11y&supportsSound

I don't see it or hear it
![Screen Shot 2019-12-11 at 8 39 50 PM](https://user-images.githubusercontent.com/1902116/70671378-6e35b480-1c56-11ea-88f0-b11636df9025.png)

**Comment by terracoda** [comment]
This is not critical for interviews next week, but would be nice.

**Comment by jessegreenberg** [comment]
Sounds good, I asked the question in the design doc but hadn't made any changes to the sim yet. Ill update this in the sim.

**Comment by jessegreenberg** [comment]
This is now done, I don't see "Frame" anywhere anymore.
