### ISSUE TITLE
Leaving the Show Light Spectrum box seems to continue the scene description

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#249]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/461. Found with NVDA.
When you exit the dialog box for the light spectrum, it will read a selection of the scene description, even though/if none were played before opening the dialog.
**Steps to reproduce**
1. Tab over to the Show Light Spectrum box and open it
2. Press space while highlighting the x to close it
3. Listen

**Visuals**
https://drive.google.com/file/d/1exIj1QQQzmYltvExcmsD3zPifO8q2Lqz/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.21/phet/molecules-and-light_en_phet.html?ea&a11y&supportsSound
Version: 1.5.0-dev.21 2019-12-13 19:43:51 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
May happen with the keyboard nav dialog box too, but what it reads seems much less random there.

**Comment by jessegreenberg** [comment]
Thanks, this looks strange I will investigate.

**Comment by jessegreenberg** [comment]
Ah, this is actually the same thing that is happening in https://github.com/phetsims/gravity-force-lab/issues/234 and in that issue we decided there is nothing we can do about it. Note has been added to A11y bug tracker and we are submitting a bug repiort to NVAccess about this.
