### ISSUE TITLE
Molecules stay highlighted grey

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#250]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/461. Found with NVDA.
When you select molecules using the screen reader, it causes that molecule to have a grey hover highlight when not selected. This highlight can show up on multiple molecules and does not go away from any method I have tried other than refreshing the page.
On a related note: If you press space when the screen reader is saying "bullet" focus goes away and nothing happens.
**Steps to reproduce**
1. Use the screen reader to listen to the molecule options
2. Use space to select one
3. Read over another option and use space to select it.
4. Note that using Tab does not produce the same results

**Visuals**
![multigrey](https://user-images.githubusercontent.com/41024075/70943383-fd075000-200d-11ea-8321-6154a3207edc.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.21/phet/molecules-and-light_en_phet.html?ea&a11y&supportsSound
Version: 1.5.0-dev.21 2019-12-13 19:43:51 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks, I will take a look. This is likely because we change the "over" fill on focus. But when reading with the virtual cursor we don't get any focus events. So the radio buttons are not told to update their fill.

**Comment by jessegreenberg** [comment]
I am coming back to this issue but I haven't been able to reproduce this. @KatieWoe would you mind seeing if you can make this happen?

**Comment by KatieWoe** [comment]
It doesn't seem to be happening on master.

**Comment by KatieWoe** [comment]
It does still happen on the built version the issue was reported for, so this isn't due to a firefox fix or an nvda fix.

**Comment by jessegreenberg** [comment]
OK thanks for checking @KatieWoe. I don't feel like I have time to look into what changed in our code to understand why it was fixed, but glad to hear that it isn't happening anymore.
