### ISSUE TITLE
No indication that you are at the end of the slider

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#254]
For https://github.com/phetsims/QA/issues/461. Noticed on iPadOS 13.3 VO.
When moving the slider that controls light intensity, there is an indication that you've reached the left end when it says the light is off, but there is no indication that you've reached the right end. The last few just say "fast." I think it would be better if it gave some indication that you are at the end by saying "fastest."
![offbutnofastest](https://user-images.githubusercontent.com/41024075/70953138-a148c100-2025-11ea-9128-a1f93281fa15.gif)

**Comment by jessegreenberg** [comment]
Nice thought @KatieWoe, this is a design recommendation so assigning to @Matthew-phet and @terracoda to review.

**Comment by terracoda** [comment]
I like the recommendation of a single-value region for "fastest". 
However, we also need to think about how the slider values are going to be represented on the state descriptions.

For example,
- "Currently, paused in observation window, ‪Visible‬ light source emits photons slowly and directly at ‪Water‬ molecule."

I'll mark for design meeting.

**Comment by jessegreenberg** [comment]
For tomorrows interviews we will add "fastest" at the right most position.

**Comment by jessegreenberg** [comment]
'fastest' added in the above commit @terracoda
