### ISSUE TITLE
Screen Reader describes molecule that isn't there

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#256]
For https://github.com/phetsims/QA/issues/461. Noticed on iPadOS 13.3 VO.
This may be intended, and if so feel free to close. I noticed that the scene description will describe what the original molecule looks like even if it is broken up or off the screen entirely.
![brokenmolecule](https://user-images.githubusercontent.com/41024075/71018857-7b1f3180-20b6-11ea-82b5-f36de9560669.png)
![outofviewdescribed](https://user-images.githubusercontent.com/41024075/71018858-7b1f3180-20b6-11ea-9666-0b835cc3d106.png)

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, @Matthew-phet @terracoda can you verify that this is the desired design?

**Comment by terracoda** [comment]
I am not sure of the context. I will check.

**Comment by jessegreenberg** [comment]
> Preference during meeting is to have these list items disappear when this happens.

Done in the above commit @terracoda.
