### ISSUE TITLE
Add slow motion

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#262]
@terracoda recently performed some interviews on the new a11y features for this simulation, and reported that at least one of the users had some problems with the play/pause/step functionality.  It was suggested that adding a "Slow Motion" feature would likely alleviate the problem, because slow motion would allow more descriptions to finish, and because users that are navigating via keyboard would probably opt to use this rather than moving back and forth between the play/pause/step controls and other interactive elements.  This suggestion was discussed in a meeting on Jan 15 2020 with @arouinfar, @jessegreenberg, @Ashton-Morris, @Matthew-phet, @terracoda, and @BLFiedler.  The consensus was to go ahead and implement the feature.

**Comment by jbphet** [comment]
The control arrangement in Pendulum Lab may serve as a good model for what is implemented here.  It looks like this:

![image](https://user-images.githubusercontent.com/3082831/72480131-a2e7df00-37b3-11ea-8dc4-7997a81dfd15.png)

**Comment by jessegreenberg** [comment]
Slow motion controls added in the above commits.

@arouinfar can you please review the behavior? Animation speed at slow motion is 1/3 of normal speed. Does this seem like an appropriate slow down?

**Comment by arouinfar** [comment]
@jessegreenberg 1/3 speed looks pretty good to me. 

@terracoda can you also take a look at the slow motion speed? I'm not sure what plans there are for the descriptions when in slow motion, but the current speed in master seems reasonably slow (1/3 of normal speed).

**Comment by jessegreenberg** [comment]
We reviewed the speeds last week, alerts worked well with slow motion at this sim speed.
