### ISSUE TITLE
Vibration sound produces an audible click

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#263]
This is a child of issue #233.

There are several loops used in the sound design, but one - vibration - produces a click much of the time when it starts.  I don't hear this with any of the other loops.

**Comment by jbphet** [comment]
When I look at the .wav file for this sound, it starts at the top of a max amplitude moment.  Here is a screenshot from Audacity:

![image](https://user-images.githubusercontent.com/3082831/72850733-ff8d4300-3c66-11ea-83a9-22a4bed33cbb.png)

I'm going to try editing this sound so that it starts at a low amplitude point instead and see if that helps.

**Comment by jbphet** [comment]
The edits did make the problem go away.  Here is a post-edit screenshot:

![image](https://user-images.githubusercontent.com/3082831/72851935-39ac1400-3c6a-11ea-9173-0ab632d010ce.png)

**Comment by jbphet** [comment]
@Ashton-Morris - can I get a .wav file for this sound that matches what I did above but includes five cycles and is thus at least a second long?  I think that will help to ensure that the user never hears any gaps in the loop.  Also, please make sure that there is no silence at the end so that it loops well.

**Comment by Ashton-Morris** [comment]
Sure here is an edited .wav file [vibration](https://drive.google.com/open?id=1CpbEnamabFhqfXK7PAaa74wPEhwuXqQ0)

**Comment by jbphet** [comment]
@Ashton-Morris - I just looked at the revised sound file, and I guess I wasn't very clear on my request.  Can I get a version of this sound that begins at the lowest amplitude value instead of the highest and includes a total of five cycles?  Starting at (or near) the max amplitude is contributing to the audible click, as described in https://github.com/phetsims/molecules-and-light/issues/263#issuecomment-576926712 above.

**Comment by Ashton-Morris** [comment]
@jbphet Sure: This[ .wav starts at the lowest amplitude](https://drive.google.com/open?id=1ssZ4EjantEsa94PpFTtJa498FjNcnWh2)

**Comment by jbphet** [comment]
Thanks @Ashton-Morris - that's perfect.  I've added the `.wav` file as and asset and I derived an `mp3` file from it that fades in at the beginning, and I no longer notice the click.  Closing.
