### ISSUE TITLE
Change "See" to "Examine" in Light Source pop-up button help text

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#266]
A static state change - rewording. The Show Light Spectrum provides a learner a detailed diagram and description of the light spectrum - a way to examine the spectrum.
 
Change current Help Text (change is bolded):  
- See details of full light spectrum.
- To: **Examine** details of full light spectrum.

**Comment by jessegreenberg** [comment]
Done in the above commit.
