### ISSUE TITLE
Change help text for photon rate slider

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#268]
Please change help for photon rate slider from
- "Adjust to emit photons at different rates."
To:
- "Adjust photon emission rate from slow to fast."

Rationale: Better wording now that the rates are:
- light source off
- very slow
- slow
- fast
- fastest

**Comment by arouinfar** [comment]
That all looks reasonable to me.

**Comment by jessegreenberg** [comment]
Done in the above commit.
