### ISSUE TITLE
Change "See" to "Examine" in help text for Show Light Spectrum button

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#269]
As discussed and decided in Feb 4 description design meeting:
For Show Light Spectrum, pop-up button, please update the help text to:
- "Examine details of full light spectrum."

Changing from "See" to "Examine".

**Comment by jessegreenberg** [comment]
This is done
![image](https://user-images.githubusercontent.com/6396244/74268409-d562fa00-4cd5-11ea-9c07-08fa4cb6b054.png)
