### ISSUE TITLE
MAL Sound Features Video Script & Recording

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/molecules-and-light#270]
Make sound features video script and review with team

https://drive.google.com/open?id=15am5708SUVtuKrX2X91zEbkkj8qSlYHkAtYOaMMUnT4

Recording will happen after.

**Comment by BLFiedler** [comment]
Script complete, ready for review (still need a finalized version of MAL before recording can begin)

https://docs.google.com/document/d/15am5708SUVtuKrX2X91zEbkkj8qSlYHkAtYOaMMUnT4/edit?usp=sharing

**Comment by BLFiedler** [comment]
Emily posted to the Waves Intro issue:

> BLFiedler - please bring this to MAL sound meeting tomorrow. We can confirm there that there will be no enhanced sounds, and also consider other descriptors for the sounds. I'm not sure about Ping or wubwub, etc. but others might prefer them, or have a few quick brainstormed ideas for different ones.

**Comment by BLFiedler** [comment]
Waiting on a version that is sound complete before doing a proper recording, but I tried a version where I let the sim play in the background as I talked over it (as opposed to pausing to talk). It's smoother, and might be okay with some balancing between my voice and the sim. What do you think @emily-phet ?

https://drive.google.com/file/d/1h-mwvxKXN4ihhryPXngyR9sf56KcrqvP/view?usp=sharing

**Comment by emily-phet** [comment]
@BLFiedler - A few thoughts:
- With the goal of attempting, when possible, to demonstrate the sounds following a similar flow we might want a teacher or learner to use when using the sim...I think it would make sense to start by going through each of the light sources first. You can do this quickly, pointing out that there is a difference tone for each, and (if you like) the pitch change mapping. 
- Next, I think indicating the sounds associated with photon absorption (emphasizing bending, rotating, etc. over molecule absorption/re-emission). For this, it make sense to set up the scenario, pause during an absorption event, and then pause the sim while you describe what sounds were heard. Then unpause and move on to the next scenario. Let me know what you think about this approach.

**Comment by BLFiedler** [comment]
@emily-phet To the first point, do you mean to just discuss and click through the radio buttons with the light source off? It's difficult to isolate photon sounds with starting molecule (CO) in the way, since it will interact w/ both Micro & IR. The reason I have the light source pitch mapping at the end is I have already blown up NO and the screen is empty so I can focus solely on the photon "bell-like" sounds and the radio button mapping.

And the second point sounds fine to me. There is also a universal hotkey to pause/play (!) now, so I don't need to click is every time if that seems distracting.

**Comment by emily-phet** [comment]
@BLFiedler - If it's helpful to you, you might start the video with a different molecule in place. Though don't if it would require reworking later parts of the script to accommodate. 

Even if molecule interaction interferes a bit, I still think it's worth bringing teachers attention to the different photon sounds early. Since they'll be hearing a lot of photon sounds throughout the video and while using the sim, it will be good if they have already attended to the fact that there is intentional and thoughtful differences across these as they're viewing the rest of the video.

**Comment by BLFiedler** [comment]
Alright - this is what I would consider my "best" attempt so far. I gave up trying to do one cut for the entire script, so there is a little editing here (the unpredictability of the photon absorption really catches you out with some strange pauses. I challenge you to identify where I cut out 3 visible photons ;) ). 

Pulling in @terracoda to have a listen too if she has time.

https://drive.google.com/file/d/1AdygxbKV7gIkfNgmKdcKuxvjiS6QXnva/view?usp=sharing

**Comment by terracoda** [comment]
@BLFiedler, I'd say that's a cut! I think you did a fantastic job!
It looked and sounded really smooth to me.

There are plenty of places where you are not talking over the sounds, and I think it makes it beneficial that you talk over the sounds at certain points. It makes it clear that this sim has continuous sound once the photon button is pressed and the sim is not paused.

Nice job!

**Comment by BLFiedler** [comment]
Hearing that MAL is publishing soon, I've gone ahead and uploaded this version to YouTube and added captions to be added to the website alongside the MAL publication. I'll close when that is done, but if there are any problems here, let me know and I can address ahead of that (or fix after).
