### ISSUE TITLE
Changes to screen summary due to new timing controls 

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#273]
Related to changes in https://github.com/phetsims/molecules-and-light/issues/267

Please change the static description in the screen summary describing the Control Area from:

- From the Control Area you can use buttons to pause/play and step forward what’s happening in the observation window. You can also access details about the light spectrum and reset the sim.

TO (bolded text changed):
- **The Control Area has radio buttons to switch between normal and slow Play Speeds, and buttons to Play, Pause and Step Forward.** You can also access details about the light spectrum and reset the sim.

**Comment by jessegreenberg** [comment]
Done in the above commit @terracoda.
