### ISSUE TITLE
Sound Design Consideration: Stretching/Bending sound

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#283]
Based on the first of 5 interviews we might want to consider making the bending/stretching sound more rubberbandy sounding.

Feb-P1 thought the bending/stretching sound sounded like fast spinning.
Feb-P1 really liked the the spinning and glowing sounds and the break-apart pop sound. Though P1 did mention the break-apart sound could be easy to miss.

We have 4 more interviews scheduled up until Feb 28. Sound design team can hold off for more feedback as they wish.

**Comment by jbphet** [comment]
Assigning to @terracoda to log her input once the interviews are complete.  I'm also removing myself as an assignee, since there is nothing that I need to do on it at the moment.  @terracoda - please assign back to me once the interviews are complete and you've added your input.

**Comment by terracoda** [comment]
Feb-P2 commented that the stretching sound sounded like a rubberband, which is good from an association perspective.
Feb-P3 commented that the rotation and glowing sounds made sense, and did not comment on stretching/bending sound.

So, no serious negative feedback on be stretching/bending sound. The latest version that adds some stereo effect might address Feb-P1's comment.

**Comment by terracoda** [comment]
@jbphet, I am not sure if anything more needs to be done. There's a new version of the sound for the stretching/bending since the interview, right?

**Comment by jbphet** [comment]
> There's a new version of the sound for the stretching/bending since the interview, right?

No, there isn't.  It's the same sound as before, and we were waiting on the results of the interviews to decide whether to work on creating and reviewing alternate sounds.

Based on your comments above, I think we should try the stereo versions of this sound and see if we're happy with that.  I'll leave this open and assigned to me, and we can decide at the next review meeting what's next.

**Comment by terracoda** [comment]
@jbphet, regarding my comment
> There's a new version of the sound for the stretching/bending since the interview, right?

I meant to say, there is a new version of the stretching/contracting sound that includes some type of "stereo". If so, I think we should use those and that might address the comments from Feb-P1.

**Comment by jbphet** [comment]
@terracoda - thanks for the clarification.  Yes, we are planning to integrate stereo sounds for the stretching/bending and for rotation, and plan to review them at next week's sound design meeting.

**Comment by jbphet** [comment]
Based on subsequent interviews, we've decided that this sound is good as is but we are going to try to enhance it a bit by adding stereo, see #284.  Closing.
