### ISSUE TITLE
Consider no "pop-up" for Dialog Buttons

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#286]
Some screen readers (at least Voice Over) describes `aria-haspopup = "true"` as a menu pop-up. For VoiceOver users the PhET Menu button is the perfect example of pop-up button, whereas the Light Source Spectrum as a pop-up button is confusing.

We could/should re-investigate to see what the latest supported option there is for buttons that pop-up dialogs. For example, it this well supported?
- `aria-haspopup = "dialog"`

And consider not using `aria-haspopup = "true"` only for menu-type things that pop-up a list of options.

**Comment by terracoda** [comment]
@jessegreenberg, this change would be common code, so this issue might need to move once we discuss at next meeting. Feel free to share with other devs if you have time to investigate.

**Comment by jessegreenberg** [comment]
Sounds good, ill test `aria-haspopup="dialog"` to determine its output.

- [ ] JAWS (Chrome)
- [ ] NVDA (Firefox)
- [ ] iOS VO
- [ ] VO Safari

**Comment by jessegreenberg** [comment]
With aria-haspopup="true":
  - NVDA + Firefox: "Show Light Spectrum menu button, sub menu"
  - VO + Safari: "Show Light Spectrum, menu pop up, button"
  - VO + iOS Safari: "Show Light Spectrum, Pop up button, Menu Pop up"
  - JAWS + Chrome: 

With aria-haspopup="dialog":
  - NVDA + Firefox: "Show Light Spectrum button, sub menu
  - VO + Safari: "Show Light Spectrum, Dialog pop up, button"
  - VO + iOS Safari: "Show Light Spectrum, Pop up button, Dialog pop up"
  - JAWS + Chrome:

**Comment by terracoda** [comment]
Ok, thanks @jessegreenberg, `aria-haspopup="dialog"` is not well supported.

Let's go with no indication of pop-up in the code for dialog buttons. I can explore some generic help text that might be more helpful than what aria can currently provide.

**Comment by jessegreenberg** [comment]
@terracoda  I was just about to write that we should switch to `aria-haspopup="dialog"` since at least it was better on VO. But you would rather remove all `aria-haspopup` attributes on buttons that open a dialog (including keyboard help button and so on)?

**Comment by terracoda** [comment]
Well, if we assume the in the future things will get better rather than worse, sure let's switch to aria-haspopup="dialog" for dialogs.

**Comment by terracoda** [comment]
I think that 2 years ago, there was no support, so maybe things are already getting better :-) And I suppose we could file bug reports to push things along :-)

**Comment by terracoda** [comment]
@jessegreenberg, go ahead with `aria-haspopup="dialog"`. Assigning over to you.

**Comment by jessegreenberg** [comment]
Sounds good! `aria-haspopup` is used in master.  Anything else for this issue @terracoda?

**Comment by terracoda** [comment]
@jessegreenberg, you convinced me to use `aria-haspopup="dialog"` instead of aria-haspopup="true".

Please go ahead and change. I am seeing ` aria-haspopup="true"` and NOT `aria-haspopup="dialog"`

**Comment by jessegreenberg** [comment]
Thanks for checking! Fixed in the above commit.
![image](https://user-images.githubusercontent.com/6396244/77550575-a8cf0000-6e87-11ea-9d72-913719e8dc39.png)

Closing.
