### ISSUE TITLE
Change to initial interaction hint

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#287]
Please change to:
- Look for photon rate slider to explore. 

And if sim is paused:
- Look for photon rate slider to explore. If needed, set sim to Play under Timing Controls.

**Comment by jessegreenberg** [comment]
Addressed in the above commit. While running:
![image](https://user-images.githubusercontent.com/6396244/75164707-2ec42380-56ef-11ea-9d13-2ee310b41ee6.png)

While paused:
![image](https://user-images.githubusercontent.com/6396244/75164745-3c79a900-56ef-11ea-83ef-06f78f114123.png)

**Comment by jessegreenberg** [comment]
Provided in this version:
https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.31/phet/molecules-and-light_en_phet.html
