### ISSUE TITLE
Reset the observation window photon wavelength changes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#288]
From user interviews with blind participants, there was some confusion when changing the photon wavelength while there are old photons that exist in the window that can be absorbed.  For instance, Having CO2 in the window while there are infrared photons, then changing to visible photons, it was confusing when the CO2 molecule absorbed an infrared molecule after visible photons were selected.

To change this, the design team would like to try "resetting" the observation window when photon wavelength changed. This will include clearing all photons in the observation window and resetting the active molecule.

**Comment by jessegreenberg** [comment]
This was done in the above commit.

@arouinfar and @terracoda can you please review this behavior change?

**Comment by arouinfar** [comment]
@jessegreenberg the behavior looks fine to me, but I thought we decided only to clear the photons; not reset the molecule. @terracoda @BLFiedler?

**Comment by BLFiedler** [comment]
I believe we thought it'd be best to try to only clear the photons and let the molecule continue whatever it was doing, assuming it's incapable of absorbing a new photon while it's undergoing an interaction with a previously selected light source.

**Comment by jessegreenberg** [comment]
I see, thanks, I misunderstood. Corrected in the above commit. Back to @arouinfar @BLFiedler or @terracoda to verify.

**Comment by arouinfar** [comment]
Looks good in master @jessegreenberg

**Comment by terracoda** [comment]
Looks like it is working great to me!

**Comment by terracoda** [comment]
Since I am the last person. I am closing.
