### ISSUE TITLE
Move Reset Molecule button to under the Photon Rate slider's Help Text

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#290]
In #280 we moved the button and in #265 we are renaming it. This little button is a tricky one.

let's try once again placing it in the PDOM after the Photon Rate slider:

**Sample Pseudo Code:**
H3: Observation Window
‪
UL
Li: O2 and O out of view. Reset molecule to make more observations.

INPUT type range: Ultraviolet Photon Rate, slider
P for Help text (for slider): Set photon emission rate.

Button: Reset Molecule 

**Note** in the A11y View, the `aria-valuetext` for the slider value should come before the Reset Molecule button.

**Comment by jessegreenberg** [comment]
Done in the above commit
![image](https://user-images.githubusercontent.com/6396244/75360434-c78ba800-5883-11ea-9894-7a1b30ea7af0.png)

> in the A11y View, the aria-valuetext for the slider value should come before the Reset Molecule button.

This is a general issue with aria-valuetext and the a11y-view. Ill make an issue in chipper, if there isn't one already.

**Comment by terracoda** [comment]
@jessegreenberg, maybe it is time to think about how we could put Object Responses like current aria-valuetext over above the Context Responses, or interwoven with the the Context responses?

**Comment by jessegreenberg** [comment]
Interesting! I moved your comment to https://github.com/phetsims/chipper/issues/896 since we work on this more generally there. Closing this issue.
