### ISSUE TITLE
Sound: Add stereo-reverb version of molecule break apart sound

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/molecules-and-light#292]
[Here is the new file](https://drive.google.com/open?id=1XXWE_7DrHBXDdIxLa9QA6X4juWmR4TO-)

**Comment by Ashton-Morris** [comment]
Currently asking for access so I can assign people.

**Comment by jbphet** [comment]
This sound has been integrated into the dev version https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.34/phet/molecules-and-light_en_phet.html.  I personally think it is *way* more noticeable new.  @Ashton-Morris, @emily-phet, @BLFiedler, and @Matthew-Moore240 - please have a listen and let me know (in the issue) if you're good with this new version.  I found it best to compare it to the previous version, which can be found at https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.32/phet/molecules-and-light_en_phet.html.

**Comment by Matthew-Moore240** [comment]
Sounds good to me.

**Comment by BLFiedler** [comment]
I found that really enjoyable. Just closing my eyes and listening, I really got the sense the sound was moving! Same goes for the rotation.

It doesn't seem to me just using the right ear that anything is lost, but maybe others have another feeling or want the volume tuned.

**Comment by arouinfar** [comment]
I think dev.34 is a definite improvement. It sounds more dynamic to me, and I don't find that I lose anything when listening with just one earbud.

**Comment by jbphet** [comment]
Discussed in the 3/10/2020 sound design meeting and the team members who haven't yet commented agreed that the new sound is an improvement.  We're going to go with it, at least for now.  Closing.
