### ISSUE TITLE
Try removing some of the high harmonics on the "glow" sound

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#298]
During the 3/10/2020 sound design meeting, Wanda recommended experimenting with the removal of some of the high harmonics from the glow sound.  The members of the team noted that several interviewees had commented that the sound stood out, and maybe it stands out a bit too much.  @Ashton-Morris said he could try a few things to moderate this, and then we can review the revised versions and decide whether to replace the current sound.

Assigning to @Ashton-Morris to create the revised sounds.

**Comment by emily-phet** [comment]
Ideal timeline for this would be to have a new sound in the sim to consider, or sounds (if there are multiple) to review so a final decision could be made next Tuesday (March 17th).

**Comment by wandita** [comment]
hello! yes i think minimizing the harmonic it already has may make it bright  ( auditorily) and in context, and comfortable to the ear.

**Comment by wandita** [comment]
is the video working?

**Comment by emily-phet** [comment]
@wandita - I don't think Ashton has created a new version of this sound yet. He may link it here, or it may not be available until Tuesday's design meeting...depending on when he gets to it. 

@Ashton-Morris if you could link it here in advance, that would great!

**Comment by Ashton-Morris** [comment]
Here you go

[absorb-loop-low-harmonics-reduction.mp3](https://drive.google.com/open?id=1lrt_GHru9EVHFDfrNOa3b-sK2RWSL_Aq)
[absorb-loop-medium-harmonics-reduction.mp3](https://drive.google.com/open?id=1YvDaaCGfavxLwXPtBhwTJGn4v9Bx7MZ2)
[absorb-loop-large-harmonics-reduction.mp3](https://drive.google.com/open?id=1aUP2iFI3onQuThiJQAOo2GB6SwMY4uhl)

**Comment by jbphet** [comment]
@wandita said to me (via email):

> I think the best one is the low harmonic reduction. But that is my humble opinion. You may need more users.

I like that one as well, so I will move forward with integrating it.

**Comment by jbphet** [comment]
Approved in the 3/24/2020 sound design meeting, closing.
