### ISSUE TITLE
Consider new alert and help text for Reset Molecule button

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#301]
I think the "Reset Molecule" label is better. I am still not sure where this button should go, but that said, I think we can improve the Context Response and dynamic hints in the screen summary and Observation Window.

I've updated the design doc and suggest the following changes to the strings that we are currently using:
1. Context Response - change from "Look for Reset Molecule button."
 - To: **Change molecule or l**ook for Reset Molecule button.
2. Dynamic string added to end of Molecule description in Observation Window, change from “Look for Reset Molecule button to make more observations.”
  - To: “**Change molecule or l**ook for Reset Molecule button  to make more observations.”
3.  As a dynamic string in the screen summary.
 Change from:  "Currently, in observation window, Ultraviolet light source emits photons fast and directly at empty space. Look for Reset Molecule button."
  - To: "Currently, in observation window, Ultraviolet light source emits photons fast and directly at empty space. **Change molecule or l**ook for Reset Molecule button.

**Comment by terracoda** [comment]
@Matthew-Moore240, let me know if you think this is better.
@BLFiedler, @arouinfar, @jessegreenberg  and @emily-phet are free to comment as well.

We could easily switch the phrasing like "Look for Reset Molecule button or change molecule." And "Look for Reset Molecule button or change molecule to make more observations." I just thought the verb "Change" easily cues that something has to change to continue.

**Comment by terracoda** [comment]
Posting in visual of where these phrases show up.
![Screen Shot 2020-03-12 at 1 54 53 PM](https://user-images.githubusercontent.com/1902116/76543728-dec4bb00-6469-11ea-865b-1a48a39a0f02.png)

**Comment by Matthew-Moore240** [comment]
Yeah that looks really good to me!

**Comment by terracoda** [comment]
Or, just discussed with @emily-phet maybe this is better,
- "Reset or change molecule."
- "Reset or change molecule to make more observations."

**Comment by terracoda** [comment]
@Matthew-Moore240, shall we go with this instead?

**Comment by Matthew-Moore240** [comment]
Yeah those corrections look good.

**Comment by terracoda** [comment]
1. Context Response - change from "Look for Reset Molecule button."
 - To: "Reset or change molecule."
2. Dynamic string added to end of Molecule description in Observation Window, change from “Look for Reset Molecule button to make more observations.”
  - To: “Reset or change molecule to make more observations.”
3.  As a dynamic string in the screen summary.
 Change from:  "Currently, in observation window, Ultraviolet light source emits photons fast and directly at empty space. Look for Reset Molecule button."
  - To: "Currently, in observation window, Ultraviolet light source emits photons fast and directly at empty space. Reset or change molecule.

**Comment by terracoda** [comment]
@jessegreenberg, assigning over to you for implementation.

**Comment by jessegreenberg** [comment]
OK thanks, this was done in the above commits. @Matthew-Moore240 can you please review? Anything else for this issue?

**Comment by terracoda** [comment]
Looks good @jessegreenberg.
