### ISSUE TITLE
Light Spectrum dialog - content create/review

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#304]
@BLFiedler is completing the content for the Light Spectrum dialog in the design doc.

We should review:
- [x] @terracoda 
- [x] @Matthew-Moore240

**Comment by BLFiedler** [comment]
H2 completed on my end for now. Left an indented bullet list as well as a version laid out in sentence structure.

**Comment by terracoda** [comment]
@jessegreenberg, @BLFiedler has completed teh detailed descriptions for the light spectrum dialog here in the [design doc](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit?pli=1#heading=h.2a5d8quri1dk).

Is it possible to do a nested list structure like Brett created under the bolded text, "H2: Frequency and Wavelength Ranges"? I think that structure could make reading and skipping lines easier for screen reader users.

**Comment by terracoda** [comment]
@Matthew-Moore240, you are still welcome to rad the content and comment if you like.

**Comment by jessegreenberg** [comment]
It is possible. The descriptions have been added to the sim, and the PDOM looks like this when the spectrum dialog is open:
![image](https://user-images.githubusercontent.com/6396244/77446251-8cb65a80-6dc4-11ea-87d9-087351f058a2.png)

Back to @BLFiedler and @terracoda for review.

**Comment by BLFiedler** [comment]
Looks great to me. I'll leave it up to Taliesin if that seems like it'll work well to navigate via screen reader.

**Comment by terracoda** [comment]
@BLFiedler, for the Visible light description, how do you feel putting the rainbow description as the first sub-bullet? It is new info, not following the same pattern as the light sources. I think it could be skipped over easily if it is the third bullet. 

With the change, it would read like this:
- Visible, tiny range: 
   - Shown from low energy to high energy as a rainbow of colors (dark red to red to orange to yellow to green to blue to violet).
  - Frequencies 4 times 10 to the 14 to 7 times 10 to the 14 Hertz.
  - Wavelengths 7 times 10 to the negative 7 to 4 times 10 to the negative 7 meters. 

And since the entire graph is shown low to high energy, do you think it is necessary to repeat that for visible light? How does this sound?
- Visible, tiny range: 
   - Shown as a rainbow of colors (dark red to red to orange to yellow to green to blue to violet).
  - Frequencies 4 times 10 to the 14 to 7 times 10 to the 14 Hertz.
  - Wavelengths 7 times 10 to the negative 7 to 4 times 10 to the negative 7 meters. 

@BLFiedler assigning to you to verify wording and order changes.

**Comment by BLFiedler** [comment]
> Visible, tiny range:
Shown as a rainbow of colors (dark red to red to orange to yellow to green to blue to violet).
Frequencies 4 times 10 to the 14 to 7 times 10 to the 14 Hertz.
Wavelengths 7 times 10 to the negative 7 to 4 times 10 to the negative 7 meters.

I think that's a good idea. I agree it could be easily skipped. Everything (frequencies, wavelengths, light spectra) is listed low to high energy, so I agree it's not necessary to re-state.

**Comment by terracoda** [comment]
@jessegreenberg, could you adjust the content so it is the same as the group in https://github.com/phetsims/molecules-and-light/issues/304#issuecomment-604079253

**Comment by jessegreenberg** [comment]
OK, change made in the above commit! Can this be closed @terracoda?

**Comment by terracoda** [comment]
Looks good. Closing time.
