### ISSUE TITLE
New Interaction Hint needed in Screen Summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#306]
Related to #302 (review of PDOM), please update the initial interaction hint from:
- "Look for photon rate slider to explore. {{If needed, set sim to Play under Timing Controls.}}" to:
- "Turn light source on to explore. {{Make sure sim is set to Play.}}"

The dynamic parts of the hint are in curly braces, and should work the same as the current implementation.

**Comment by jessegreenberg** [comment]
The interaction hint in master is currently
> Turn light source on to explore.

And the design document currently says
> Note: With new UI Context responses for light source button, dynamic help text no longer needed.

@terracoda can you comment on whether this issue can be closed or the dynamic part should still be included?

**Comment by terracoda** [comment]
@jessegreenberg, yes, apologies, @Matthew-Moore240 and I just discussed the new context responses today. So if the new context responses will work, we won't need this help text to be dynamic.

I'll mark this issue onhold.

**Comment by terracoda** [comment]
If the context responses are cleared fro implementation we can come back to this issue.

**Comment by jessegreenberg** [comment]
@terracoda @Matthew-Moore240 is this issue still on hold?

**Comment by terracoda** [comment]
No stale. Closing.
