### ISSUE TITLE
Best name for Light Sources radio group?

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#307]
Hi @arouinfar, @BLFiedler and @Matthew-Moore240 , in issue #296 we are changing the Photon Rate slider to be a button. @Matthew-Moore240 and I settled on calling it a Light Source button see https://github.com/phetsims/molecules-and-light/issues/296#issuecomment-598404599.

With "Light Source" used on the button, would it make better sense to change the name of the radio group, and its help text?

**Suggested Options:**
1. Light Spectrum: Choose spectrum of light for observation window ordered low to high energy.
2. Light Spectrum Options: Choose spectrum of light for observation window ordered low to high energy.

If you think I am over-thinking this, I am happy to leave as-is:
- Light Sources: Choose light source for observation window ordered low to high energy.

Please vote:
@arouinfar 
- [x] leave as is
- [ ] change to option 1
- [ ] change to option 2
- [ ] posted other idea

@BLFiedler  
- [x] leave as is
- [ ] change to option 1
- [ ] change to option 2
- [ ] posted other idea

@Matthew-Moore240   
- [x] leave as is
- [ ] change to option 1
- [ ] change to option 2
- [ ] posted other idea

**Comment by terracoda** [comment]
"Choose light for light source ordered low to high energy." - just another thought for help text.

**Comment by BLFiedler** [comment]
My gut reaction to calling any of those a light "spectrum", is that the result of you pressing that is a piece of equipment that emits a photon (which exists at a single wavelength from that spectrum). Spectrum implies something continuous. I think I would side with leaving as is. 

Should the "Light Source Button" have some indication that it's an on/off button?

**Comment by terracoda** [comment]
@BLFiedler, the on/off issue is being worked on in #296 
Typically in a toggle button, the sates are communicated as pressed and not pressed.
I think we can do better than pressed and not pressed, but we may not have time to do better.

**Comment by arouinfar** [comment]
Thanks for checking in @terracoda. Similar to @BLFiedler, the action I associate with the radio buttons is selecting a piece of equipment (or the "source"). "Spectrum" has continuous associations that I do not think are appropriate here.

**Comment by Matthew-Moore240** [comment]
Light source button seems good to me

**Comment by terracoda** [comment]
Leaving the radiobutton group heading as "Light Sources". Thanks for the feedback.
