### ISSUE TITLE
Updates to Static Screen Summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#308]
In #302 we are checking changes to PDOM, the static part of the screen summary needs updating. @Matthew-Moore240, we need to review changes can be found in design doc.

**Comment by terracoda** [comment]
@Matthew-Moore240, I made changes in the design doc. We can discuss before next meeting.

**Comment by terracoda** [comment]
@Matthew-Moore240, I really struggled with the static part of the screen summary, what do you think of the static screen summary below? You can ignore the dynamic screen summary and the interaction hint in this issue. 

**Static Screen Summary**
> Molecules and Light is an interactive sim. It changes as you play with it. It has a Play Area  and Control Area.
> 
> The Play Area has an observation window that contains a light source and a molecule. You choose different light sources and molecules.
> 
> The Control Area has radio buttons to switch between normal and slow sim speeds, and buttons to pause and step forward actions happening in observation window. You can also access details about the light spectrum and reset the sim.

_After the "static part" there's the dynamic screen summary:_
> Currently, {{in observation window}}, {{Infrared}} light source {{is off and points}} directly at {{carbon monoxide}} molecule.

_And then the interaction hint:_
> Turn light source on to explore.

**Comment by terracoda** [comment]
@Matthew-Moore240 if you like it, please assign issue to @jessegreenberg for implementation. If you don't like please iterate and ask for help if you need it.

**Comment by Matthew-Moore240** [comment]
Yeah that looks good to me! assigning to @jessegreenberg

**Comment by jessegreenberg** [comment]
This is now up to date, closing.
