### ISSUE TITLE
Consider making MoleculesAndLightQueryParameters.slowSpeed into a constant

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#310]
The comments for `MoleculesAndLightQueryParameters.slowSpeed` say:

```
  // For testing as we decide how fast sim should play at the "slow" setting. This value is a proportion of the "normal"
  // speed, so default 0.3 means slow time moves 30% as fast as fast "normal" time.
```

Is it ready to move from this file to the constants file?

**Comment by jessegreenberg** [comment]
Thanks, and sorry, this comment should have pointed to an associated issue. Its still being discussed in #295, and I will make note of that at the comment.
