### ISSUE TITLE
Swap order of controls in TimeControlNode

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecules-and-light#311]
In today's description design meeting, we decided to put the normal/slow radio button group on the left side of the play/pause/step buttons. Reasons for the change:
* Flow wise, Normal/Slow is the more important interaction (for all users), and should come before the buttons in the tab order.
* It's nice to keep the visual and tab orders in sync.
* Moving the button group to the right side of the TimeControlNode means the buttons will come last in the tab order, and these are the least important components for screen reader users.

Current configuration:
![image](https://user-images.githubusercontent.com/8419308/76884687-b101bc80-6843-11ea-898b-8589d004e6f1.png)

With `stringTest=long` there already seems to be an appropriate `maxWidth` for the radio buttons, so moving them to the left side of the TimeControlNode should shouldn't pose any i18n issues.
![image](https://user-images.githubusercontent.com/8419308/76885319-aa277980-6844-11ea-9d89-186224a031db.png)

**Comment by jessegreenberg** [comment]
Moved to the left in the above commit.

**Comment by jessegreenberg** [comment]
@arouinfar back to you for review.

**Comment by arouinfar** [comment]
Looks good @jessegreenberg!

![Molecules and Light screenshot](https://user-images.githubusercontent.com/8419308/76886078-d98ab600-6845-11ea-9db0-8e58a5e6017a.png)
![mal](https://user-images.githubusercontent.com/8419308/76886072-d7285c00-6845-11ea-8685-f55118f7b3c3.png)

**Comment by arouinfar** [comment]
@terracoda the tab order has already been swapped with the visual order, but not sure if there are any other changes that need to be made in the PDOM for this issue.

**Comment by terracoda** [comment]
The visuals look great! I am just working on PDOM.

**Comment by terracoda** [comment]
@jessegreenberg, I need a few re-arrangements/changes to the PDOM representation of the Timing Controls.
1. Please remove aria-labelledby for the group. 
2. Please move the help text for the radiobuttons to under the Sim Speeds h4 heading.
3. Please use new non-changing help text for the Play/Pause/Step Forward buttons, and leave it after the buttons. The new help text is:
  -  Play sim at chosen sim speed, or pause sim to step forward little by little.

**Comment by terracoda** [comment]
@jessegreenberg, I swapped the order of the help text phrases for the Pause/Step Forward buttons.

**Comment by terracoda** [comment]
@jessegreenberg, I forgot the word, "photons" in the help text. I forgot to discuss this at todays meeting, but I think folks will like it. 

I am adding "photons" to https://github.com/phetsims/molecules-and-light/issues/311#issuecomment-600307078

**Comment by terracoda** [comment]
@jessegreenberg, I have totally messed up this issue. I want to keep the help text under the Pause/Play and Step Forward buttons **dynamic**, like this for now:

[[Pause]] [[Step Forward (disabled)]]
Pause sim to step photons forward little by little, or keep playing sim at chosen sim speed.

[[Play]] [[Step Forward]]
Step photons forward little by little, or play sim at chosen sim speed.

**Comment by jessegreenberg** [comment]
In the above two commits, I removed the `aria-labelledby` for the group and moved the help text for radio buttons under the "Sim Speeds" h4 heading. 

The new dynamic descriptions for the Play/Pause/Step buttons in https://github.com/phetsims/molecules-and-light/issues/311#issuecomment-600391713 are sim specific. 

I would strongly recommend that we don't use sim specific descriptions for these buttons unless we really have to. Right now these buttons are encapsulated under the TimeControlNode so it will take extra development effort to set custom descriptions for these buttons. It also sets a precedent that we need to design descriptions for these buttons for every single simulation that uses the TimeControlNode. @terracoda can we use the descriptions you have in https://github.com/phetsims/molecules-and-light/issues/311#issuecomment-600391713 but just remove the word "photons"?

**Comment by terracoda** [comment]
@jessegreenberg, hmm, one way to not have all these sim specific responses is to disable of the Pause/Play button when the the Light Source button is off.

@Matthew-Moore240 and I think that makes a lot of sense. We can discuss at tomorrow's a11y design meeting.

**Comment by terracoda** [comment]
@jessegreenberg, yes, we can remove "photons". That does generalize the help text.

**Comment by terracoda** [comment]
@jessegreenberg, you were referring to dynamic help text not the context responses.
You can remove "photons" from help text and we will discuss the context responses tomorrow.

**Comment by jessegreenberg** [comment]
Thanks very much @terracoda, that sounds great. The dynamic help text has now been added. 

In summary, I 
1) Removed the aria-labelledby for the group.
2) Move the help text for the speed radio buttons to under the "Sim Speeds" h4 heading.
3) Updated the help text for the Play/Pause/Step buttons.

Back to @terracoda to review to make sure everything is done for this issue.

**Comment by terracoda** [comment]
This all sounds wonderful @jessegreenberg!
