### ISSUE TITLE
Update to dynamic state of the sim sentence 

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#312]
Related to issue #302 and the removal of Photon Rate slider, we need to make sure the sentence describing the current state of the sim is updating correctly. The examples in the design doc are outdated.

@Matthew-Moore240, can you please test the sim and adjust the examples in the design doc. We no longer need to describes rates because we only have 1 rate. We still need cases for for on and off, and paused, and you might want to mention "slow motion" some how when the sim is set to slow.

Please reach out if you need help. I think the sentences we already designed are good, but I think they need some tweaks due to the interaction change.

**Comment by terracoda** [comment]
@jessegreenberg, @Matthew-Moore240 and I have updated the dynamic state of the sim sentence. There are examples in the design doc [close to here](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit#heading=h.lfzscx53fh1b), Dynamic State of the sim.

**Comment by jessegreenberg** [comment]
Alright, this is done in master @terracoda and @Matthew-Moore240
