### ISSUE TITLE
convert model.txt and implementation-notes.txt to .md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#313]
.md is the PhET standard for these files.

**Comment by jessegreenberg** [comment]
Thanks, done

**Comment by pixelzoom** [comment]
Look again.  Your heading formatting is messed up.

**Comment by jessegreenberg** [comment]
Thanks, a space is required after the "#" for it to format correctly, missed it because it was formatted correctly without it in the WebStorm preview.

**Comment by pixelzoom** [comment]
Yeah, the WebStorm preview isn't very accurate.  I always check it on GitHub.
