### ISSUE TITLE
Verbose vibration context response not reset after reset or page load

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#314]
@jessegreenberg, I am not sure if I already opened an issue for this bug. Apologies if this is a duplicate issue. I notice this behaviour a while ago, so it is not recently introduced.

**Issue at Normal Sim Speed**
The molecule "reactions" or context responses start off with slightly more detail, and then change to one-word descriptions.
- Bonds of molecule stretching.
- Stretching.

The verbose descriptions return after a molecule change, and after a light source change, but they do not reset after a reset (with no change in molecule or light source) nor a page reload.

I think the verbose alert should return after a reset and after a page load regardless of other interactions.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, fixed in the above commit. The alert manager is now reset when the model resets.
