### ISSUE TITLE
UI Context Responses for Light Source Toggle Switch

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#318]
Related to issue https://github.com/phetsims/molecules-and-light/issues/296#issuecomment-604038103 and issue #317 

To consistently communicate state changes and to warn users that the sim might be paused, we have the following context responses for the Light Source toggle switch.
- [Table: Light Source Toggle Switch](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit#heading=h.lnuk30zlpy3)

We will not need the "Sim paused" indications if we are able to add an option to the Time Control Node to disable the Pause/Play button when light source is switched off.

**Comment by jessegreenberg** [comment]
These have been implemented in master @terracoda! Over to you to review.

**Comment by terracoda** [comment]
With the toggle button, this sounds awesome, @jessegreenberg.

I also tested with the "switch" query parameter. In the current switch implementation on VoiceOver the states are being communicated through the browser. 

So depending on final decision (and testing in all 3 screen readers) in #296, we may need to tweak the context responses. I.e., if we go with a switch role and the state change is clearly communicated by the AT, we won't need "Photons on" and "Photons off", but we will likely still need the other parts of the responses that support the paused state and slow speed.

**Comment by terracoda** [comment]
At the MAL design meeting, @terracoda demoed these new context responses with the switch parameter and everything sounded good on VoiceOver.

@jessegreenberg, I'll close this issue. We can re-open or open new issues once we are testing the switch interaction that will be implemented in #296.
