### ISSUE TITLE
Change help text for Light Source toggle switch

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#321]
@jessegreenberg, I think this change got missed in the shuffle.

Could you change the help text for the Light Source switch from:
- Activate light source to start exploration.
to:
- Turn light source on to start photons.

**Comment by jessegreenberg** [comment]
Done: 
![image](https://user-images.githubusercontent.com/6396244/78084687-dedc1a80-7386-11ea-8a6c-31aa03c73285.png)
