### ISSUE TITLE
Reduce time from turning on photon emitter until the first photon come out

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#322]
In https://github.com/phetsims/molecules-and-light/issues/295#issuecomment-597278072 I described an issue with the way the new button operates.  In today's sound design review meeting for this sim, it was recommended that this be made into a separate, standalone issue.

Here is the original description of the problem:

> The MAL sound design team was using the button in context during today's review meeting, and we have a suggestion: There should be no, or at least a lot less, delay between pushing the button and the emission of the first photon. The current behavior, which can be seen on https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.37/phet/molecules-and-light_en_phet.html, seems a bit sluggish, and is particularly problematic when the sim is paused, then the button is pressed, and then the sim is stepped. We noticed it took around 30 steps in this case before anything happened, which is likely to frustrate users.

...to which @arouinfar reponded:

> Agreed @jbphet. Can you look into this @jessegreenberg?

**Comment by jessegreenberg** [comment]
There is a specific constant for this
```INITIAL_COUNTDOWN_WHEN_EMISSION_ENABLED = 0.3```

Should this just be removed now?

**Comment by jessegreenberg** [comment]
I think so - even when set to 0 it feels like there is a small delay because the point where photons are emitted is slightly to the left of the right edge of the emitter image.

**Comment by jessegreenberg** [comment]
Done in the above commit. @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in master @jessegreenberg!
