### ISSUE TITLE
Change initial position of photons so that they appear immediately

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#324]
Initial position of photons is to left of emitter bulb so it takes about 10 steps for the photon to become visible. @jessegreenberg to see if it is easy to change initial position.

Sound of photon emission correctly plays when photon reaches edge of emitter bulb, so I should check in @jbphet and see if any adjustments need to be made to sound after this change.

**Comment by jessegreenberg** [comment]
Done in the above commit. @arouinfar can you please review this behavior change? Before this commit photons slid into view from behind the emitter, which looked nice. But now they appear right when they are created so there is no delay when stepping, which is also good.

If this looks good to you Ill reassign to @jbphet to review the change I made to sound so that it plays right when the photon is added.

**Comment by arouinfar** [comment]
@jessegreenberg this is generally looking good, but things can be weird if switching between light sources while paused.

When the sim is playing, switching between light sources will clear the photons in the viewing window and the source will immediately release a photon. However, if the sim is paused when the light source is changed, there can be a very long gap before the next photon is released.

1. Pause sim and turn on photon source
2. Step forward once and a photon appears (great!)
3. Switch to a different photon source
4. Step forward until a photon appears. This takes nearly 50 button presses. (not so great)

**Comment by jessegreenberg** [comment]
Thanks! I was able to make this happen too. It seems inconsistent, sometimes it takes ~5 presses to appear other times ~50 as you mentioned.

**Comment by jessegreenberg** [comment]
It looks like the emission countdown timer isn't being reset when photon wavelength changes, so I suspect this is more related to #288 than changes for this issue.

**Comment by jessegreenberg** [comment]
OK, fixed above. When changing photon wavelength the countdown timer is reset so a photon is emitted right away if the emitter is on.

**Comment by jbphet** [comment]
The reason that the code was originally implemented such that the photons started behind the photon emitters (and thus were invisible when first created) is that the original design team was bothered by photons appearing fully formed in front of the emitter.  In the latest version on master, the photons are doing just that, and it is quite apparent when stepping.  I propose that we compromise a little and move the the spot where the photons pop into existence so that the edge of each photon is visible right away but not the whole thing.

**Comment by jessegreenberg** [comment]
Sounds good @jbphet, thanks. Done in the above commit, photons  look like this when first added to the screen:
![image](https://user-images.githubusercontent.com/6396244/79163106-67f24900-7dac-11ea-94bb-8da20728b1bd.png)

**Comment by jbphet** [comment]
I just tested it in the sim and it looks great - thanks @jessegreenberg!

**Comment by jessegreenberg** [comment]
Great thanks! And we got a 👍 from @arouinfar so I think this issue can be closed.
