### ISSUE TITLE
Update to Static Screen Summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#326]
To review today at MAL's Interactive Description Design Meeting:
The Static part of the Screen Summary is awkward (not active-sounding enough). I think some minor tweaks could make it a lot more fun sounding.

**Current Static Screen Summary**
> Molecules and Light is an interactive sim. It changes as you play with it. It has a Play Area  and Control Area.
>
> The Play Area has an observation window that contains a light source and a molecule. You choose different light sources and molecules.
>
> The Control Area has radio buttons to switch between normal and slow sim speeds, and buttons to pause and step forward actions happening in observation window. You can also access details about the light spectrum and reset the sim.

**Suggested Update Static Screen Summary**
> Molecules and Light is an interactive sim. It changes as you play with it. It has a Play Area  and Control Area.
>
> The Play Area **is an observation window set up with** a light source and a molecule. It has options for light source and molecule.
>
> The Control Area has **options** for how fast the action happens in the observation window including buttons to pause and step forward. You can also access details about the light spectrum and reset the sim.

After the above static screen summary, there are three more pieces that round off the full screen summary: 
1. the dynamic snap shot, 
2. the initial interaction hint, and 
3. the hint for help if it is needed. Providing these items as well as part of the issue because it is nice to have the full context of the full Screen Summary. Every word can potentially be important in setting an inviting and playful scene.

> Currently, {{Infrared}} light source is {{off}} and points directly at {{Carbon Monoxide}} molecule.
>
> Turn light source on to explore.
>
> If needed, check out keyboard shortcuts under Sim Resources.

My rationale for the update is to provide a slightly stronger invitation to play with the set up of the sim.

By describing the Play Area as **being** "_an observation window set up with_ a light source and molecule", rather than having an observation window, I feel will provide a more active invitation to learners that they can change the set up as they explore. 

BASE's screen summary is set up this way, i.e., "The Play Area is a small room...."

**Comment by terracoda** [comment]
Since this wording change is rather minor, this issue is mainly for @terracoda, @Matthew-Moore240 and @jessegreenberg to discuss at today's design meeting. That said, others are free to comment on the issue or join today's meeting to discuss.

**Comment by terracoda** [comment]
Decision to updated static screen summary.

**Comment by jessegreenberg** [comment]
I updated the screen summary as described in https://github.com/phetsims/molecules-and-light/issues/326#issue-603845486, ready for review.

**Comment by terracoda** [comment]
Looks good! Closing.
