### ISSUE TITLE
Clean up sound file names, make sure we have all the needed assets

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#328]
In https://github.com/phetsims/molecules-and-light/issues/233 we implemented the sound design for this sim.  The sound files used went through a lot of churn, so now that the implementation has been approved, we need to make sure the sound files are reasonably well named and that we have the appropriate assets around in case we ever need to modify or recreate them.

**Comment by jbphet** [comment]
@Ashton-Morris - can you please provide `.wav` files for some sounds that we don't have them for or that don't match the `.mp3` versions that we are using (see the list below)?  Also, if there are any other files related to producing any of the sounds (e.g. for Reaper), it would be good to have those as well in case we ever need to make changes.

Here is a list of the `.wav` files that we need, with their current name first and their original name second.  The asset name should match the current name:
- absorb-photon (formerly absorb-based-on-photon)
- energized (formerly absorb-loop-low-harmonics-reduction)
- break-apart (formerly break-apart-stereo-reverb)

If you're comfortable doing it, you can just commits these to the `assets` directory of the `molecules-and-light` repo.  If you'd rather I do it, please send me links to files with the correct names and I'll take care of it.  Thanks!

**Comment by Ashton-Morris** [comment]
@jbphet I tried but webstorm is having some issues with github after I did an os update. 

[I have put those files here though ](https://drive.google.com/open?id=1dII2m4KtMuZyxGShyF0rXf7ZSGUKOkq6)

**Comment by jbphet** [comment]
The files have been checked in, we should be good to go.  Closing.
