### ISSUE TITLE
Dev Link for upcoming MAL interviews

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#330]
We will do 2 more interviews to evaluate the design changes in MAL.

Please post a dev link that contains both Interactive Description and Sonification by end of day April 29, 2020.

**Comment by jessegreenberg** [comment]
@terracoda here is a dev link to the latest version. If you notice any issues please let me know.

https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.48/phet/molecules-and-light_en_phet.html

**Comment by terracoda** [comment]
@jessegreenberg, I have sound in the dev link. Thanks for sending it along.
My problem must be local.

**Comment by jessegreenberg** [comment]
OK sounds good! Closing this issue since link was prepared.
