### ISSUE TITLE
Dynamic or static help text for light source switch?

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#332]
In an interview today, our VO consultant found it a little confusing that when the Light Source was switched on the help text still said, "Turn light source on to start photons." 

We have two routes for improved clarity:
1. Keep help text static, but clarify the on/off functionality.
  - Turn light source on and off to start and stop photons.

2. Make help text dynamic:
  - Turn light source on to start photons.
  - Turn light source off to stop photons.

The consultant mentioned in today's session that because the photons are firing, it might be a little confusing or overwhelming to read "Turn light source on to start photons" when the photons are actually on.

**Comment by terracoda** [comment]
Decision: We go with option 2 - dynamic help text.

**Comment by jessegreenberg** [comment]
OK, assigning to myself to add.

**Comment by jessegreenberg** [comment]
This was done in master, assigning to @Matthew-Moore240 or @terracoda to review.

**Comment by terracoda** [comment]
Thanks @jessegreenberg, this looks and sounds great.
I think will also supports learners when the sim happens to be paused. Provides an extra reminder that things are already "on".
