### ISSUE TITLE
Can we do anything about "No and O float away?"

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#335]
Can we do anything about the context response that announces, "NO and O float away"? This is spoken as “No and O float away”, by screen reader software.

Options are:
1. Do nothing - hopefully AT will improve in the future and any confusion in the interim can be cleared up in a supported learning context.
2. Spell out the molecule pieces:
    - “Nitrogen Oxide and Oxygen float away.”

The response for the split Ozone is less problematic since O2 and O<sub>2</sub> sound the same:
    - "O2 and O float away."

**Comment by jessegreenberg** [comment]
This was also mentioned in https://github.com/phetsims/molecules-and-light/issues/255

**Comment by terracoda** [comment]
We will wait for voice reading software and web standards to improve.
