### ISSUE TITLE
Update Keyboard Shorcuts dialog with Step Forward hot key

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#338]
Related to #336, with the addition of a Hotkey for Step Forward, we need to update the Keyboard Shortcuts dialog.

![keyboard-shortcuts-dialog](https://user-images.githubusercontent.com/1902116/81099836-18ec8f00-8ee6-11ea-9819-daca546568f1.png)

**Visual content**
- When action is paused step forward little by little [Alt key] + [L]

**Accessible content**
- When action is paused step forward little by little with Alt key plus L.

JUST had a thought that for non-visual exploration bigger steps would be way more useful. @jessegreenberg would it be possible to make ALT + L do big steps instead of little ones? I'm thinking 3 visual steps for photon to reach molecule:
- Step one: leaves light source
- Step two: halfway to molecule
- Step three: at absorption point of molecule

If this is possible, the Keyboard Shortcuts dialog would need to be:

**Visual content**
- When action is paused step forward in bigger steps [Alt key] + [L]

**Accessible content**
- When action is paused step forward in bigger steps with Alt key plus L.

**Comment by jessegreenberg** [comment]
Functionality of the step forward button is being tracked in #336 so moving content there.

**Comment by jessegreenberg** [comment]
On hold until #336 is sorted since that issue may change teh descriptions.

**Comment by terracoda** [comment]
@jessegreenberg with the success of #336 and #339, please update the Keyboard dialog with the bigger steps option.

**Comment by jessegreenberg** [comment]
OK, this row of content has been added, @terracoda can you please review?

**Comment by terracoda** [comment]
Looks and sounds awesome!
![Screen Shot 2020-05-12 at 3 04 34 PM](https://user-images.githubusercontent.com/1902116/81729265-485f4680-9466-11ea-9f5f-608b0ab450bc.png)
