### ISSUE TITLE
Add sounds to play/pause/step hotkeys

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#339]

**Comment by jessegreenberg** [comment]
From #336

**Comment by jessegreenberg** [comment]
These have been added, and you made it very easy for me! @jbphet and @terracoda can you please review?

**Comment by jbphet** [comment]
I've reviewed the code, and it looks reasonable to me.  @terracoda - I'll leave it to you to verify that the behavior is what we're after.

**Comment by terracoda** [comment]
From my "non-visual screen reader" perspective this ALT + L interaction is really awesome - much preferred to the default Step Forward.

The sounds sound great to me and the number of steps across the Observation Window seem really good.

I don't know what JAWS and NVDA will say with each ALT + L key press, but VO does not mention the actual keys on key presses. With VO, if nothing is happening, I just hear the Step Forward UI sound which makes for a really nice experience. Then when something is happening, I hear the step forward UI sound on each step and the occasional context response about photons (every 4 to 8 steps). Then when a vibration is happening, I get the UI sound and a context response on every key press during the vibration. It sounds really nice to me.

I think we can close this issue.
