### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#341]
From #201, credits should be updated for next publication,

Current list:
Verified additions to Team: Wanda Diaz Merced, Brett Fiedler, Matthew Moore, Taliesin Smith, Brianna Tomlinson, Syan Zhou
 Verified Sound Design: Ashton Morris, Mike Winters

Others will be added (like around QA and such). We will modify when we get closer to final publication.

**Comment by jessegreenberg** [comment]
It is time for this. @KatieWoe @terracoda are there any other names to add to the list?

**Comment by KatieWoe** [comment]
QA: Liam Mulhall, Kathryn Woessner, Logan Bray, Jaspe Arias
These should be in alphabetical order (I was just going down the matrix).

**Comment by terracoda** [comment]
The a11y list is good, @jessegreenberg.

**Comment by KatieWoe** [comment]
QA still needs to be done for https://github.com/phetsims/QA/issues/520 @jessegreenberg

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - now that phetsims/qa#520 is done can you comment on any names that should be added?

**Comment by KatieWoe** [comment]
Just the ones in https://github.com/phetsims/molecules-and-light/issues/341#issuecomment-662132103

**Comment by jessegreenberg** [comment]
Credits have been updated in both master and the release branch.

**Comment by jessegreenberg** [comment]
Reopening - coming back to this I misread that https://github.com/phetsims/molecules-and-light/issues/341#issuecomment-663519122 meant the list in https://github.com/phetsims/molecules-and-light/issues/341#issue-621184284 rather than the list in the sim. Names in https://github.com/phetsims/molecules-and-light/issues/341#issue-621184284 need to be added and then another maintenance release should go out.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/chipper/issues/969 is currently still an issue so if I deploy a maintenance release it will remove the images used by the filter page and other things. I need to wait to deploy until that issue is fixed or someone from the website team can help manually put the images up.

**Comment by mattpen** [comment]
phetsims/chipper#969 should be fixed now and shouldn't block progress on this issue.

**Comment by jessegreenberg** [comment]
Thanks @mattpen - and it looks like the fix was made to perennial so no changes will need to be moved to the MAL 1.5 release branch. I am going to go ahead with deploying the next maintenance release of MAL.

**Comment by jessegreenberg** [comment]
1.5.2 was deployed with updates to credits.
