### ISSUE TITLE
Using the right mouse button while interacting with sim causes freeze

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/molecules-and-light#342]
<b> Test device </b>

Windows 10 Laptop

<b>Operating System</b>

Windows 10 v. 1903

**Browser**

Chrome 83.0.4103.61 (Official Build) (64-bit)

**Problem description**

For https://github.com/phetsims/QA/issues/503

This occurs when interacting with any functional part of the sim, including the pause button, reset all button, and the radio buttons. An error log does appear in the console. While holding a button down (i.e. keeping it in the depressed animation by holding the left mouse button down, or in the case of the sliders highlighted), if the right mouse button is pressed the sim will then freeze completely. 

**Steps to reproduce**

1. Use the left mouse button to hold down the reset all button, do not release the left mouse button
2. Without releasing the left mouse button, use the right mouse button

**Visuals**

![2020-05-20Mlc LghtFreeze](https://user-images.githubusercontent.com/54685448/82494040-31dc6f00-9aa6-11ea-8746-4d8580dc4e8b.gif)

<details> <summary> Troubleshooting information: </summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.50/phet/molecules-and-light_all_phet.html?zoom=true
Version: 1.5.0-dev.50 2020-05-12 15:11:56 UTC
Features missing: generatedcontent, csstransforms3d, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
Language: en-US
Window: 1576x776
Pixel Ratio: 1.21875/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

<details> <summary> An error appeared in the console as follows </summary>
molecules-and-light_all_phet.html?zoom=true:912 Uncaught TypeError: Cannot read property 'initialPoint' of null
    at Object.move (molecules-and-light_all_phet.html?zoom=true:912)
    at q.value (molecules-and-light_all_phet.html?zoom=true:912)
    at q.value (molecules-and-light_all_phet.html?zoom=true:912)
    at q.value (molecules-and-light_all_phet.html?zoom=true:912)
    at q.value (molecules-and-light_all_phet.html?zoom=true:912)
    at molecules-and-light_all_phet.html?zoom=true:912
    at e.value (molecules-and-light_all_phet.html?zoom=true:912)
    at q.value (molecules-and-light_all_phet.html?zoom=true:912)
    at q.value (molecules-and-light_all_phet.html?zoom=true:912)
    at ba.run (molecules-and-light_all_phet.html?zoom=true:912)
</details>

**Comment by loganbraywork** [comment]
Interestingly, this bug does not occur on Firefox but does occur on Edge and another unsupported Chromium browser

**Comment by KatieWoe** [comment]
Good catch @loganbraywork

**Comment by jessegreenberg** [comment]
Error is specifically "cannot read initial point of null". When I try on chrome though (unbuilt) i first get "Attempted to add an input listener that was already added", so Ill start there.

**Comment by jessegreenberg** [comment]
Also important, this only happens when zoomed all the way out.

**Comment by jessegreenberg** [comment]
In Chrome, the right mouse click doesn't send a "down" event to the browser. But it does in FF. That explains why this doesn't happen on that browser.

**Comment by jessegreenberg** [comment]
OK, this issue has been fixed in the above commit, which prevents a listener from being added to a press Pointer if it is already in the list of background presses.
