### ISSUE TITLE
"Something happening" sound will not play if started during step through

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#344]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/503. Very minor sound interruption type sound.
If you start a molecule action that has a sound associated with it (such as the molecule bending) by stepping through the paused sim, and then press play while the action is happening the sound does not play for the rest of the action. 
The sound does play in these situations: Sim is playing and action starts, pause, play; Sim is muted, action starts, unmute; and Sim is playing, action starts, pause, step through once, play 
**Steps to reproduce**
1. Set up combo that will cause a sound+action (Infrared and NO2 for example)
2. Pause the sim
3. Step through until an interaction occurs and an action starts
4. Part way through action, press play and listen

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.50/phet/molecules-and-light_all_phet.html?zoom=true
Version: 1.5.0-dev.50 2020-05-12 15:11:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment]
@jbphet, could you comment if it is possible to make the excitation sound start if Play is pressed after starting an excitation in Step Forward mode?

**Comment by terracoda** [comment]
@KatieWoe, can you confirm that you hear description in this case?

**Comment by KatieWoe** [comment]
I do (checked on nvda) Although I notice it doesn't talk about the emitted photon. Is that intended?

**Comment by terracoda** [comment]
It only says emitted on Slow speed and Step Forward. On Normal speed, there is no time fro details. The sounds are meant to take care of that. Missing one excitation or one emission sound is likely not a show breaker. 

That said, it will be nice to hear what @jbphet has to say about this issue.

**Comment by KatieWoe** [comment]
I'll take a much closer look when I get to the a11y screen reader parts of the testing.

**Comment by jbphet** [comment]
> @jbphet, could you comment if it is possible to make the excitation sound start if Play is pressed after starting an excitation in Step Forward mode?

Yes, this could be done.  The tricky part would be synchronizing the sound with the oscillations, but I think we should do it anyway and not worry about having perfect synchronization (the sounds could probably be synced too, but this would be *much* more complicated).

I think I'll just go ahead and work on this and have you two (@terracoda and @KatieWoe) test it on master and, if we like it, we'll make it a part of the final release.

**Comment by jbphet** [comment]
Actually, it looks like the fix that I did for https://github.com/phetsims/tambo/issues/105 also addressed this problem.  @KatieWoe and @terracoda - can you please test on master and see if the behavior there is better and addresses the reported problem?  If so, please mark this as "fixed-awaiting-deploy" and unassign.  That way we can make sure to test it before the final re-publication.

**Comment by KatieWoe** [comment]
This does seem fixed on master

**Comment by terracoda** [comment]
Yep, it sounds good for me. I'll go ahead and close. @KatieWoe, please re-open if I was not supposed to close.

And thanks @jbphet!

**Comment by KatieWoe** [comment]
It can be closed as long as you don't need it tested for in an upcoming rc or dev test.
