### ISSUE TITLE
Mobile VO reading things that are not in sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#356]
From #349 - @KatieWoe mentioned that reading from the top with two finger gesture swipe with iOS VoiceOver included lots of links and other things that were not in the simulation page. See https://github.com/phetsims/molecules-and-light/issues/349#issuecomment-634940123.

Video: https://drive.google.com/file/d/1ctYMVSDFXtzJe5YUk7p1wDQZgw-fiNHd/view?usp=sharing

**Comment by jessegreenberg** [comment]
Unfortunately I cannot produce this bug. I have tried on my iPad Air 2 and my iPhone 8. In the video I hear "phet-dev, button" "Safari version, button", "PhET free online physics, chemistry..., button", something with "?profiler", "john-travoltage, button", "Frequently Visited, heading"...

It sounds like Safari history or settings or something. Were these open right before you tested @KatieWoe? Is this still happening? If so, how frequently?

**Comment by KatieWoe** [comment]
I don't believe so, but it is certainly possible. It doesn't seem to be doing it now. In fact, it seems to be reading from the correct spot now? Not sure what changed.

**Comment by jessegreenberg** [comment]
OK, very strange. I have noticed sometimes that VoiceOver will read content from a previous window, like once I had VO on while dialing a phone number, and VO continued to read buttons after I had closed my calling app.

Anyway, I feel comfortable closing this, do you @KatieWoe?

**Comment by KatieWoe** [comment]
Sure
