### ISSUE TITLE
Verify that movement during arrow keys and mouse wheel looks good in RC 1.5.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#361]
For the molecules-and-light RC https://github.com/phetsims/QA/issues/513.

@KatieWoe suggested that there was too much movement, and the movement was too slow. Movement speed during arrow key presses and mouse wheel control was modified to snap to destinations a bit faster.

Fix was handled in https://github.com/phetsims/scenery/issues/1062. Changes for the scenery issue were merged into a release branch `molecules-and-light-1.5`.

This issue is just to verify that the change looks OK in the release branch in the next RC.

**Comment by KatieWoe** [comment]
Looks good in https://github.com/phetsims/QA/issues/520 on Win 10 Chrome Closing
