### ISSUE TITLE
Inconsistencies with Mac Scrolling

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#362]
Discussed with @jessegreenberg over zoom.
Macs have a Command key, which does most of what Ctrl does on a PC. It also has a key called Control. Which of these buttons controls zoom commands in the sim seems inconstant. Control is needed if you are scrolling to zoom. Command is needed if you are using +/-/0.
Seen on Mac 10.12 Safari

**Comment by jessegreenberg** [comment]
We decided that there is nothing that needs to be done for this issue. "Command" is the conventional key to initiate zoom with keyboard controls on a mac. What is atypical is that we have "control" plus two-finger-scroll gesture triggering zoom on Mac as well. On other web pages, this just scrolls as if "control" were not pressed.

But we decided that this difference was OK, and very unlikely to confuse users. And we didn't think it was worth a platform check to disable zooming on a Mac if control was pressed down.

Closing this one as wontfix.
