### ISSUE TITLE
Sim took one minute to load on Firefox

### ISSUE THREAD

**Issue by muedli** [phetsims/molecules-and-light#365]
<b>Test Device</b>

Personal Devices: MacBook Air, Desktop PC

<b>Operating System</b>

macOS 10.15.5, Windows 10 1909

<b>Browser</b>

Firefox 78.0.2

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/513. The sim is taking way too long to load on Firefox for me. When I timed it, it took one minute. This might be because of my garbage internet, but the sim is loading reasonably quickly on other browsers for me. 🤷‍♂️

<details>
<summary><b>Troubleshooting Information</b></summary>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-rc.2/phet/molecules-and-light_all_phet.html
Version: 1.5.0-rc.2 2020-07-09 20:53:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Language: en-US
Window: 1920x1007
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Hmm, thanks for reporting. phet-dev is often very slow for me so I suspect it is related to that. On both windows Firefox and Chrome the sim takes about 10 seconds to load. Actually, with the Firefox dev tools I can see how long is spent getting the sim from the server:
![image](https://user-images.githubusercontent.com/6396244/87568368-8c9fda80-c693-11ea-92a2-4b6acbf0a6e0.png)

And once that request completes, the sim loads almost instantly. I wouldn't think there is anything special in this sim that would cause it to take longer than any other PhET sim.

@muedli can you please try again in Firefox, but record network time like in the above image? To do so, open the Firefox dev tools and click the "Network" tab. Then refresh the page and it should start recording automatically. If all the time is spent in the first "GET" it is almost certainly all in the time it takes to get the ~1.3 MB sim and not in loading javascript.

**Comment by muedli** [comment]
I recorded the network time and the sim is loading really fast now. It's taking about three seconds now. I'm guessing it just has to do with my internet. I think it's safe to close this issue.
