### ISSUE TITLE
Full Screen Alt+k and Alt+l sound

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#366]
**Test device**
Jordan
**Operating System**
Mac 10.13.6
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/513
When in full screen on safari, pressing the alt+k or alt+l buttons leads to the "wrong/you can't do that" donk sound. The command still occurs.

**Steps**
1. Open full screen with the phet menu while in safari
2. Use the alt+k and alt+l commands
3. Compare to other tab commands.

**Comment by jessegreenberg** [comment]
OK, I tried the `preventDefault` workaround that was successful with arrow keys, but it didn't work here. Unfortunately this is just another case of item 24 in the quirk tracking document.
>[Safari, Fullscreen] Using keyboard in fullscreen mode will sometimes make Safari play an error “bonk” sound. At this time there is nothing we can do about this. This should never happen for arrow keys, however. (e.g. space/enter don’t work in https://github.com/phetsims/gravity-force-lab/issues/254 and https://github.com/phetsims/molarity/issues/210#issuecomment-584412281)

Closing.
