### ISSUE TITLE
iPad VO convenience at end of Light Spectrum dialog

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#368]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 13.6
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/513
Once VO reaches the end of a dialog (in this case, the Light Spectrum dialog) swiping reads the last line again, rather than looping back to the top of the dialog. This means that, in order to leave the dialog at this point, a user must swipe backwards several times, or visually tap the x to return focus there. They may be able to bipass this by swiping two fingers up, then halting VO as it starts to read from the top. But it may be worth looking into, especially if it would be a simple fix.

**Comment by jessegreenberg** [comment]
This is a nice thought @KatieWoe but it is unfortunately not something we can control. On MacOS VoiceOver there is actually a user setting for this called "Allow cursor wrapping" which will move the cursor to top of the page after reading the last thing. But this option is not available in iOS VoiceOver.

Closing.
