### ISSUE TITLE
Scene description says to turn on light, even when it is already on

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#369]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 13.6
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/513
When reading through the scene description, it will say `Turn light source on to explore.` even when the light source is already on.
**Visual**
![turnonlight](https://user-images.githubusercontent.com/41024075/87724935-91d75500-c779-11ea-9ae2-fc58c95fba93.gif)

**Comment by terracoda** [comment]
We could have made this initial hint dynamic, but decided against it.
The likely scenario for non-visual access is that a learner will be reading from top to bottom, and while they can back and rad from top again after turning on the light source, in most cases they won't.

If the hint gets them playing with the light source on/off switch, it is doing its job.

I think, we can leave as is. I really don't like making hints and help text dynamic unless absolutely necessary.

The help text that directly supports the on/off switch is indeed dynamic.

@Matthew-Moore240, any thoughts to add?

**Comment by terracoda** [comment]
Or @jessegreenberg, any thoughts to add?

**Comment by Matthew-Moore240** [comment]
Yeah I think we can leave it as is, I think it would be a very rare scenario for this to confuse a learner.

**Comment by terracoda** [comment]
@jessegreenberg, I'll go ahead and close. You can re-open if you need to.
