### ISSUE TITLE
VO Full Screen describes sound in another tab

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#370]
For https://github.com/phetsims/QA/issues/513. Mac 10.15 Safari.
Unsure if this is an issue with the sim or with VO. When in full screen, VO would come up with an alert that a github background tab was making sound, even though the sim was the only tab and no such background sound could be heard.
![Image from iOS](https://user-images.githubusercontent.com/41024075/87814800-a66f2800-c821-11ea-9b18-caa3fe555ac0.jpg)

**Comment by terracoda** [comment]
That is really weird @KatieWoe.

**Comment by KatieWoe** [comment]
Yeah, I couldn't figure out what it was talking about. Sorry I don't have much else to add to the issue. It didn't cause any major problems that I could find, other than it being wrong. It did repeat it periodically.

**Comment by jessegreenberg** [comment]
Hmm, this is very strange. Likely not something that we can control but an issue with VoiceOver or Safari reporting sound from the wrong tab. Ill do some searching.

**Comment by jessegreenberg** [comment]
I wonder if any HTML5 elements controlling audio are not in the full screen element.

**Comment by jessegreenberg** [comment]
Hey, it looks like this was reported here: https://github.com/phetsims/molarity/issues/157

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/molarity/issues/157#issuecomment-554150953 I reported that this was fixed in master in Molarity, but I am seeing the same behavior in molarity now as well.

**Comment by jessegreenberg** [comment]
OK, the bug is happening in the following html:
```html
<div id="content">
    <audio
        controls
        src="bensound-summer.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</div>

<button id="button">Fullscreen</button>

<script>
	document.getElementById( 'button' ).addEventListener( 'click', () => {
		document.getElementById( 'content' ).webkitRequestFullscreen();
	} )
</script>
```

**Comment by jessegreenberg** [comment]
I just tried playing a youtbe video in full screen mode with VoiceOver, and VoiceOver said "Youtube started playing audio in a background tab." So I think this is just a weird VO thing.

In my testing so far I wasn't able to get VO to read the incorrect tab name, but I don't expect there is anything for us to do sim-side about that either.

I recommend we close as `wontfix` after adding this to our list of screen reader quirks. @terracoda does this seem OK to you?

**Comment by jessegreenberg** [comment]
We reviewed this issue during meeting today and agreed this seems like a strange VO quirk and agreed that we shouldn't spend any more time investigating.

**Comment by jessegreenberg** [comment]
I added the issue to the bug tracker, see https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/edit
