### ISSUE TITLE
Need new screenshot and thumbnail for latest version of MAL

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#371]
@jessegreenberg, great that MAL is published! Hip, hip, hooray!

You may already know that there is no thumbnail on the filter page and an out-of-date screenshot on the sim page.

I am not sure of this is a website issue or a sim issue. Please advise.

**Comment by terracoda** [comment]
Maybe this is related to #223?

**Comment by jessegreenberg** [comment]
Thanks @terracoda - I can't remember if there is an automated way to create the screenshot or if I need to do it manually. Ill take a look.

As for the filter page I don't know why it isn't showing up there and will probably need some help from someone more knowledgeable about the website.

**Comment by jessegreenberg** [comment]
OK @KatieWoe is familiar with how to make the new thumbnail and said she would do it, thanks! @KatieWoe can you please make the image from the master branch and put it in the 1.5 branch as well?

**Comment by jessegreenberg** [comment]
I discussed the missing image on the filter page with @chrisklus. We verified that the build of MAL did not generate the icon with width of 420, the one used by that page. We noticed that other sims had these images added at different times than the build, indicating that they were added manually. I am not sure what the long-term solution should be, but it seems like we should be building the 420 width image every production build.

In the meantime, we are going to wait until the new screenshots are ready, then locally run `grunt build-images` and manually put the the missing images in the latest build directory. I will assign to @chrisklus once screenshots are ready.

**Comment by KatieWoe** [comment]
The above commits should do it. Screenshots and alts are replaced. Some changes made due to new photon rates, so old screenshots couldn't be fully matched.

**Comment by jessegreenberg** [comment]
Awesome, thanks @KatieWoe.

@chrisklus we the images are ready to be added.

**Comment by jessegreenberg** [comment]
OK, 1.5.1 was just published which updated the screenshot image. We are still looking into the missing image for the filter page.

**Comment by jessegreenberg** [comment]
Alright, @chrisklus was able to manually put the missing image into the build directory so that it shows up on the filter page. Would be good to get to the bottom of this soon so that it doesn't happen on next publication. However, MAL specific things are done. Closing this issue. Thanks for pointing out the missing image @terracoda.
