### ISSUE TITLE
TimeSpeedProperty valid values don't match Time Speed radio buttons

### ISSUE THREAD

**Issue by Denz1994** [phetsims/molecules-and-light#374]
Discovered during https://github.com/phetsims/scenery-phet/issues/607:

In the studio view of MAL, searching for "TimeSpeedProperty" shows `Valid Values: Fast, Normal, Slow`. However, the radio buttons are limited to only "Normal" and "Slow". Selecting the "Fast" option in the studio view will deselect both radio buttons in the sim view and doesn't seem to change the sim speed.

I would expect the "Fast" option to not be present in the studio view as a valid value. Assigning responsible dev to investigate.

See this [comment](https://github.com/phetsims/scenery-phet/issues/607#issuecomment-634230315) under the "Studio" content for more context and a potential solution.

**Comment by jessegreenberg** [comment]
Thanks @Denz1994 fixed in the above commit, only valid options in studio now:
![image](https://user-images.githubusercontent.com/6396244/93911740-c7943f00-fcd0-11ea-922e-5a8f7b79a3eb.png)
