### ISSUE TITLE
Need latest dev version with Prefs Menu & Interactive Highlights

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#393]
I would like a dev version of the latest Molecules and Light that contains the Preferences Menu and access to Interactive Highlights. Then I will post this on the Inclusive Prototypes page.

@jessegreenberg, assuming this would be very quick?

I look on PhET Dev and couldn't find a version with the Preferences Menu, though I see that on Master.

**Comment by terracoda** [comment]
Actually, I will the latest dev versions for a few more sims...
- OL
- RIAW
- Molarity
- GFL regular

Should I create a new issue in each sim?

**Comment by jessegreenberg** [comment]
Sounds good, can you create one issue in a11y-research (or somewhere else if that is batter) listing the sims you need?

**Comment by terracoda** [comment]
Moved to https://github.com/phetsims/a11y-research/issues/186, so closing.
