### ISSUE TITLE
photons are visible before they should be

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#77]
Somewhat related to https://github.com/phetsims/molecules-and-light/issues/32 ...

For 2 of the 4 lamps, you can see photons before they should be visible. They appear just to the right of the lamp's body, rather than looking like they are coming out rightmost part of the lamp (bulb or nozzle, depending on the lamp).   See the screenshots below, where I've added arrows to point to the photons that shouldn't be visible.

This was a problem in the Java version too. There are a few easy solutions to this, any of them is acceptable, (1) is the easiest:

(1) layer a black rectangle between the lamp and the photons
(2) using clipping, if you think that's more elegant
(3) move the position where a photon first appears further to the right
(4) redesign the lamp images so that you can't see the photons in these situations (#32)

![lamp1](https://cloud.githubusercontent.com/assets/3046552/5516505/94460d7c-885f-11e4-8ef6-be0d72b85dc4.png)
![lamp2](https://cloud.githubusercontent.com/assets/3046552/5516506/97a266aa-885f-11e4-8b54-20d9ae34a6ba.png)

**Comment by jessegreenberg** [comment]
The new ultraviolet emitter no longer has this issue, but it still persists for the microwave emitter.  For now I have included a small rectangle between photons and emitters.  Options 1 or 4 above may still cleaner solutions.  I can look into a clipping area if we do not want to redesign the microwave emitter to make the nozzle wider.

**Comment by jessegreenberg** [comment]
I sent an email to @arouinfar asking if it would be feasible to increase the nozzle width on the microwave emitter.  Keeping this open until we decide the best plan.

**Comment by arouinfar** [comment]
I widened the microwave nozzle, and sent the asset files to @jessegreenberg. Let me know if this size will work. 

![image](https://cloud.githubusercontent.com/assets/8419308/5822312/381ede40-a090-11e4-8fc0-7fb5e5955498.png)

**Comment by jessegreenberg** [comment]
The new emitter now covers photons so they do not appear prematurely.  The new image and assets have been added to the sim.  This issue is now resolved for all photon emitters so I am closing.
