### ISSUE TITLE
Photons and molecules visible behind viewing window border

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecules-and-light#78]
When photons and molecules escape the viewing window, they appear under the border instead of completely disappearing. It's most noticeable when pausing the sim and using the next frame button to advance the motion. This issue is present in dev.2.

![image](https://cloud.githubusercontent.com/assets/8419308/5879627/10a65c84-a2ee-11e4-9e19-27edfeab2514.png)
![image](https://cloud.githubusercontent.com/assets/8419308/5879640/23f883a2-a2ee-11e4-941e-8e30cb3a2ad4.png)

@jessegreenberg can consult with @jbphet to address this issue.

**Comment by jessegreenberg** [comment]
Molecules and Photons should now disappear completely at the window boundary.  Reassigning to @arouinfar for review.

**Comment by arouinfar** [comment]
It's still present in dev.3. Did you fix the issue after it was published, @jessegreenberg?

**Comment by jessegreenberg** [comment]
Yes, this was pushed after dev.3 was published.  Sorry, I am a little unclear about how PhET structures dev testing.  I just asked @samreid and @ariel-phet how I should handle issues like this.

**Comment by arouinfar** [comment]
No problem, @jessegreenberg. There's a way to see the latest version while working on site. Ariel will show me later this week, and I'll verify then.

**Comment by arouinfar** [comment]
Looks good, closing.
