### ISSUE TITLE
Move Return Molecule button to the left

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecules-and-light#79]
The right side of the Return Molecule button appears too close to the border of the viewing window. The button should be moved a bit to the left, so the top and right padding are equal. This issue is present in dev.2

![image](https://cloud.githubusercontent.com/assets/8419308/5879765/3084721a-a2ef-11e4-96f5-26f6ecce3ba7.png)

**Comment by jessegreenberg** [comment]
The 'Return Molecule' button has been moved to the left and corrected to its position before commit f9e7c8b389fe425ec23b34a6cf7a8ed58ce9e549.

![capture](https://cloud.githubusercontent.com/assets/6396244/5894928/6e71faf4-a4cd-11e4-8d01-dc52f19915e6.PNG)

Reassigning to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks good! Closing.
