### ISSUE TITLE
Return molecule button stays displayed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecules-and-light#80]
1. Choose ultraviolet as the emitted wave (turn it on, too) and ozone as the molecule.
2. The ozone will break and fly off the screen to prompt the "Return Molecule" button.
3. If the button is not pressed and the user switches to a different molecule, the button stays displayed.
4. Switching to a third molecule has the button disappearing.

Note that if the user switches to nitrogen dioxide in step 3 (which also breaks from ultraviolet) the button will properly go away the instant the molecule is broken, but not before then.

Tested on Win8.1 browsers for 1.0.0-dev.3

Troubleshooting information:
Name: Molecules and Light
URL: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.3/molecules-and-light_en.html
Version: 1.0.0-dev.3
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by arouinfar** [comment]
I also noticed this issue on my Mac (OS X 10.9.5, latest Chrome). Here are a few screenshots.

After first ozone fragment leaves the screen, the button appears
![image](https://cloud.githubusercontent.com/assets/8419308/5944836/4b314920-a6e7-11e4-9a67-7183011216f2.png)

Selecting a different (non-dissociative) molecule, the button stays on screen
![image](https://cloud.githubusercontent.com/assets/8419308/5944964/68514a22-a6e8-11e4-9b07-6178f1a38921.png)


The Return Molecule button will disappear once it's clicked.

**Comment by phet-steele** [comment]
It also persists after clicking reset all.

**Comment by jessegreenberg** [comment]
Thanks for catching this! It should be resolved in dev.5.  Reassigning to @phet-steele for review.

**Comment by phet-steele** [comment]
I haven't seen the button persist through molecule switching, looks fixed!
