### ISSUE TITLE
FF images

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecules-and-light#81]
This sim looks pretty bad on FF 35. Here's some FF/Chrome comparisons from Win8.1 directly, but the images are similar to Win7.

FF
![ffinfra](https://cloud.githubusercontent.com/assets/5863899/5945190/f8ea948e-a6e9-11e4-9e36-df6131b7e9e9.png)

Chrome
![chromeinfra](https://cloud.githubusercontent.com/assets/5863899/5945240/4a162fa8-a6ea-11e4-924f-69649d992a41.png)

FF
![ffultra](https://cloud.githubusercontent.com/assets/5863899/5945219/27d7dcc0-a6ea-11e4-952a-7efc8f2db663.png)

Chrome
![chromeultra](https://cloud.githubusercontent.com/assets/5863899/5945262/658385b0-a6ea-11e4-812e-fe93dc880128.png)

Troubleshooting information:
Name: Molecules and Light
URL: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.3/molecules-and-light_en.html
Version: 1.0.0-dev.3
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jessegreenberg** [comment]
I notice this in IE as well, loaded images are not anti-aliased.

**Comment by jessegreenberg** [comment]
I scaled down the image files manually to assist with anti-aliasing in FF and IE.  The loaded images should look better in dev.5.  Reassigning to @phet-steele for review.

**Comment by phet-steele** [comment]
They do look better. Not as amazing as Chrome, but yes they are better :+1:
