### ISSUE TITLE
Border for wavelength graph in "Show Spectrum" window disappears

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/molecules-and-light#82]
Test device: ASUS
Operating System: Win 8.1
Browser: Chrome 41
Problem description:
After opening the Show Spectrum window, hitting close momentarily removes part of the border for the wavelength graph.

Steps to reproduce:
Open sim
Select Show Spectrum
Select Close

Screenshots:
![molecule issues light spectrum](https://cloud.githubusercontent.com/assets/5631059/5963249/c1b9f72a-a7a7-11e4-8e8f-4112e4427f71.png)
Troubleshooting information (do not edit):
Name: Molecules and Light
URL: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.3/molecules-and-light_en.html
Version: 1.0.0-dev.3
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.17 Safari/537.36
Language: en-us
Window: 1366x681
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jessegreenberg** [comment]
Sorry, I am not able to reproduce this.  Is there any more information about when this happens?

**Comment by jessegreenberg** [comment]
I was not able to reproduce this isssue, reassigning to @orejolaphet for review.  Please let me know if you observe this problem in dev.5 as well.

**Comment by orejolaphet** [comment]
@jessegreenberg, sorry for the late reply, but I verified that the issue was still occurring for dev.4. 
The issue is no longer present in dev.5, what ever changes occurred fixed it on my machine. Closing.
