### ISSUE TITLE
Making the photon source sliders look more grabbable

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecules-and-light#83]
In interviews, students often click on several things before locating the slider on the photon source.

A few changes we'd like to make
- When the photon source is turned off, the bulb should be dimmed out. The goal is to cue users that something must be done to turn the source on.
- Changing the shape of the slider to mimic the shape of a switch and look more textured.
- Brightening the color of the slider to make it more eye-catching.
- Making the gradient track thinner to help the slider stand out a bit more.

Screenshots:
![flashlight-slider-off](https://cloud.githubusercontent.com/assets/8419308/5985269/5ed5babc-a89d-11e4-9f86-8e5fd399df58.png)
![flashlight-slider-on](https://cloud.githubusercontent.com/assets/8419308/5985270/5ed611d8-a89d-11e4-82be-ae42d8b2f154.png)

An email has been sent to @jessegreenberg containing the asset files for the sources in "off" mode.

**Comment by jessegreenberg** [comment]
Emitter bulbs get dimmed when the photon source is turned off.  The slider gradient track is now thinner and the color of the slider thumb is now brighter.  Bullets 1, 3, 4 above have been completed.  

![capture](https://cloud.githubusercontent.com/assets/6396244/6015777/52060670-ab36-11e4-9752-f29017bb9782.PNG)

![capture2](https://cloud.githubusercontent.com/assets/6396244/6015779/54e44c6c-ab36-11e4-9748-1fc3d1fd5de9.PNG)

I will ask another developer about the best way to change the shape of the slider thumb, though I believe it will require changing some common code in HSlider.

**Comment by jessegreenberg** [comment]
@arouinfar, I also notice that the gradient tracks in your provided screenshots fade in from a softer grey rather than black, is this a desired feature as well?

**Comment by arouinfar** [comment]
@jessegreenberg, the flashlight is looking great! The gradient looks a bit too dark when fading to black, so fading to gray is preferable. Sorry I forgot to mention this tweak, but nice catch.

**Comment by jessegreenberg** [comment]
The gradient now fades to grey as in the mockup.  A node has been drawn for the thumb on the slider and is ready to be added when we make the appropriate changes to HSlider.  It looks like the following:

![newslider](https://cloud.githubusercontent.com/assets/6396244/6136281/9afe997c-b12c-11e4-8b2c-02b01e2cc2a1.PNG)

**Comment by pixelzoom** [comment]
> when we make the appropriate changes to HSlider.

What are the proposed changes to HSlider?

**Comment by jessegreenberg** [comment]
The new

**Comment by jessegreenberg** [comment]
The requested thumbNode shape cannot be drawn with current options parameters in HSlider.  A possible change could be create an optional parameter for the thumbNode so any node or shape could be used for the thumb.

**Comment by pixelzoom** [comment]
An option to provide an alternative thumb seems useful.

**Comment by jessegreenberg** [comment]
Great, I made a simple change to HSlider to get it working.  I can send it to you if you would like to review my change.  HSlider is a heavily used user interface so I would also understand if you rather I not touch this code.  Either way, should I make this an issue in sun?

**Comment by pixelzoom** [comment]
Yes, please make a sun issue.  If you have push permission on sun, feel free to make the change. Otherwise send my a patch and I'll take care of it.

**Comment by jessegreenberg** [comment]
I have moved the issue to sun.  I do not have permissions to push to sun so I will send you my patch, thanks for the help.

**Comment by jessegreenberg** [comment]
New thumbs have been added to mimic the shape of a switch, and they are present in dev.5.  This should conclude the desired design changes listed above.  Reassigning to @arouinfar for review.

**Comment by arouinfar** [comment]
The slider thumb is looking good. I have one more request -- in my original post, the gradient extends slightly beyond the track of the slider. This was done intentionally to help the slider thumb stick out a bit more. Can you please extend the gradient (but not the track itself) to be a bit wider?  I've included some screenshots below. Reassigning to @jessegreenberg.

Off:
![image](https://cloud.githubusercontent.com/assets/8419308/6275277/0218343c-b83b-11e4-90af-85c8c887c1e4.png)

All the way on:
![image](https://cloud.githubusercontent.com/assets/8419308/6275279/0cb8f6c4-b83b-11e4-9c68-0291c061825a.png)

**Comment by pixelzoom** [comment]
This feature request is not supported by sun.HSlider, and will be non-trivial to add.

**Comment by arouinfar** [comment]
Thanks for your input, @pixelzoom. I didn't realize this would be non-trivial since the sliders in Color Vision are similar to what I've requested.

![image](https://cloud.githubusercontent.com/assets/8419308/6276705/fa96b5ac-b845-11e4-98c7-8991c82056fb.png)

**Comment by arouinfar** [comment]
@pixelzoom is there a workaround that could involve artwork rather than making changes to HSlider?

**Comment by jessegreenberg** [comment]
I believe this is possible without making changes to HSlider.  As in Color Vision, the gradient is just a Rectangle separate from HSlider so this request should be possible.  I have made the change and the sliders now look like the following when fully on and off.

![cap](https://cloud.githubusercontent.com/assets/6396244/6277882/958e8392-b84f-11e4-91f1-09416c3ad80c.PNG)

![cap2](https://cloud.githubusercontent.com/assets/6396244/6277886/9a16fc14-b84f-11e4-9cdb-ecb0a19f14bd.PNG)

**Comment by arouinfar** [comment]
Thanks, @jessegreenberg! It looks great. Can you publish a new dev version to be used in interviews next week?

**Comment by jessegreenberg** [comment]
Yes, certainly.  I will let you know when a new dev version is published.

**Comment by jessegreenberg** [comment]
I have published this change in version dev.6.  Assigning this to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks great! Closing.
