### ISSUE TITLE
Sim is missing PhET Icon.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/molecules-and-light#87]
This sim is missing the PhET Icon in the bottom right corner.
Viewed on 
-10.9.4 Safari 7.0.2
-Win 8 Chrome 41
![screen shot 2015-02-17 at 11 31 30 am](https://cloud.githubusercontent.com/assets/5631059/6234508/9ecfa21e-b698-11e4-84e2-89e93178ac17.png)

**Comment by jessegreenberg** [comment]
Thanks! PhET icons have been added in dev.6.  Assigning to @orejolaphet for review.

**Comment by jessegreenberg** [comment]
Icons have been added as of version dev.6, closing this issue.
