### ISSUE TITLE
Poor iPad2 Performance

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#91]
There are some minor performance issues on the iPad2.  Specifically, I notice that the sim seizes when a molecule hits the bottom of the observation window before being removed:

![img_0027](https://cloud.githubusercontent.com/assets/6396244/6433866/367f482e-c037-11e4-9f74-5e03cc6b93d8.PNG)

The sim stops just long enough to be noticeable.  The most noticeable trait is that the atomic bonds lag behind atom positions after the sim momentarily stops:

![img_0025](https://cloud.githubusercontent.com/assets/6396244/6433900/0bca1c5c-c038-11e4-9235-d214bfafebc6.PNG)

**Comment by jbphet** [comment]
@jessegreenberg - can you note the dev version on which these problems were observed so that we know what to compare to as we start to make optimizations?

**Comment by jessegreenberg** [comment]
This issue was first observed on version dev.7.   I just ran through all dev versions dev.1 - dev.7 and the issue seems to persist for versions.

**Comment by jessegreenberg** [comment]
General iPad2 performance is related to issue #89.

**Comment by jbphet** [comment]
During the 7/30/2015 developer meeting we decided that if the performance is good on iOS8 and okay on iOS7, this issue can be closed.

**Comment by jessegreenberg** [comment]
Performance on iPad2 for iOS7 and iOS8 seems great.  Tested iOS8 on my iPad and iOS7 on Lave.  Closing.
