### ISSUE TITLE
infrared-source-off.png missing on GitHub

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecules-and-light#92]
I can't tell if it needs to be there (in which case it should be checked in), or if the reference to it is old. Prevents building of the sim.

**Comment by jessegreenberg** [comment]
Sorry about that, I just checked in the 'off' images as they are in use once again.  Reassigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
