### ISSUE TITLE
Poor iPad3 Performance

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#93]
This is closely related to #91, which documents some performance issues iPad2.

These issues were experienced on version 1.0.0-dev.7 (http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.7/molecules-and-light_en.html).

All issues were found on PhET's iPad3 named "Disessa", which was running iOS version 8.1 (12B410) as of this writing.

**Comment by jbphet** [comment]
First, as with issue #91, the load times are somewhat long, though I think I've seen them longer on some other sims.  I manually timed three loads using a stopwatch app and got the following values:

+ 12.05s
+ 12.18s
+ 12.68s

**Comment by jbphet** [comment]
The animation is quite jerky when the "halo" is going on and off.  In the screenshot below, you can see the setup for this test, and can also see that the delay caused by the halo becoming visible caused inconsistent spacing in the photon stream.  When switching back and forth from the setup shown to a setup with a test molecule that doesn't interact with visible light, such as oxygen, the animation goes from jerky (with nitrogen dioxide) to smooth (with oxygen), which is why I believe that this is related to the halo going off and on.  Also, @jonathanolson said that opacity is often a performance killer, and the halo is set to 0.6 opacity.

![mal-ipad3-01](https://cloud.githubusercontent.com/assets/3082831/6472102/398379ce-c1ad-11e4-9fe8-7cce48bbb15b.PNG)

**Comment by jessegreenberg** [comment]
Removing the halo gradient does improve performance for the interaction between visible photons and NO2.  Without the semi-opaque 'halo' the photon absorption behavior performs as well as any other strategy.  

However, removing the gradients does not affect any of the performance issues described in issue #91.

**Comment by jbphet** [comment]
We should use the ?profiler option and quantify the performance with and without the halo to determine whether doing the work to replace it with something else would be warranted.

**Comment by jessegreenberg** [comment]
I used the ?profiler option to get some quantifiable performance data.  Here are the results:

The following are profiler results with a steady stream of visible photons being fired at nitrogen dioxide so that semi-transparent 'halo' gradients are produced.

On chrome:

	frames per second: fluctuates from 56-60
	avg frame time: 17 ms
	longest frame time: 33 ms
On Firefox:

	frames per second: fluctuates from 54-60
	avg frame time: 17 ms
	longest frame time: 42 ms
On Internet Explorer:

	frames per second: 60
	avg frame time: 17 ms
	longest frame time: < 30 ms
On iPad2 (iOS 8.1.3, Safari 600.1.4):

	frames per second: fluctuates from 24 to 28
	avg frame time: 42 ms
	longest frame time: 199 ms

The following are profiler results with a steady stream of visible photons being fired at nitrogen dioxide, but with the halo gradients disabled.
On chrome:

	frames per second: fluctuates from 58-60
	avg frame time: 17 ms
	longest frame time: < 30ms
On Firefox:

	frames per second: 60
	avg frame time: 17 ms
	longest frame time < 30 ms
On Internet Explorer:

	frames per second: 60
	avg frame time: 17 ms
	longest frame time: < 30 ms

On iPad2 (iOS 8.1.3, Safari 600.1.4):

	frames per second: fluctuates between 29 and 31 frames per second
	avg frame time: 36 ms
	longest frame time: 52 ms

**Comment by jessegreenberg** [comment]
The profiler data above was taken with semi-transparent halo nodes completely removed.  Below is some data with semi-transparent halo gradients replaced with opaque yellow circles. 

![capture](https://cloud.githubusercontent.com/assets/6396244/6544245/fc7fac5a-c503-11e4-810d-6154435768b7.PNG)

I thought it would be good to get a gauge for performance when halo visibility is still effected by the Excitation Strategy, but with opacity and gradients removed.

On Chrome, Internet Explorer, and Firefox, profiler data exactly the same as above.

On iPad2 (iOS 8.1.3, Safari 600.1.4):

	frames per second: fluctuates between 29 and 31 frames per second
	avg frame time: 34 ms
	longest frame time: 53 ms

**Comment by jessegreenberg** [comment]
I thought it would be beneficial to test the performance of radial gradients and opacity values seperately.
The following is profiler data for iPad2 with halos that have radial gradients and are fully opaque.

![capture](https://cloud.githubusercontent.com/assets/6396244/6548045/91be5c8c-c5b1-11e4-96f3-c2e4581db9a4.PNG)

On Chrome, Internet Explorer, and Firefox, profiler data exactly the same as above.

On iPad2 (iOS 8.1.3, Safari 600.1.4):

	frames per second: 27
	avg frame time: 38 ms
	longest frame time: 152 ms

The following is profiler data for iPad2 with halos that have 0.6 opacity and no radial gradients.

![capture](https://cloud.githubusercontent.com/assets/6396244/6548069/d0456512-c5b2-11e4-8539-811b99918a15.PNG)

On iPad2(iOS 8.1.3, Safari 600.1.4):

	frames per second: 26
	avg frame time: 45 ms
	longest frame time: 186 ms

**Comment by jessegreenberg** [comment]
Summary of the results above:

Changing the halo gradient and opacity has no effect on performance in Chrome/Firefox/Internet 
Explorer.

On iPad2, fps is not heavily effected by the how the halos are represented.  Frames per second 
constant at around 25-30 fps on iPad2 for all tested halo styles.

Both transparency and radial gradients cause the single frame time to spike up from the average when a halo is made visible on the scene.

Removing transparency and radial gradients improve performance by reducing the maximum observed frame time from ~200ms to ~55ms.

**Comment by ariel-phet** [comment]
@jessegreenberg you probably want to get some time with @jonathanolson as he tends to be our expert at optimizing performance

**Comment by jbphet** [comment]
I added back the halo but used a gradient that fades to transparent with no opacity.  Performance seems to be better, but may have been impacted by other recent changes.  Here is the commit: https://github.com/phetsims/molecules-and-light/commit/216c230940cdc5a42853c638b0d923c88df622a3.

**Comment by jbphet** [comment]
During the 7/30/2015 developer meeting we decided that if the performance is good on iOS8 and okay on iOS7, this issue can be closed.

**Comment by jessegreenberg** [comment]
Performance is great on iPad3 iOS8, just tested with diSessa.  molecules-and-light does not use WebGL so we can assume that it will perform well on iOS7 for iPad3 as well. Closing.
