### ISSUE TITLE
Tweaks to Microwave and Visible Sources

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecules-and-light#95]
I would like to make a few small adjustments to the artwork for the microwave and visible sources. The slider looks a bit crowded on the microwave source, so I have widened the body a little (while maintaining the same overall width). This will allow there to be more little negative space around the slider than there is in the latest dev version (below).

![image](https://cloud.githubusercontent.com/assets/8419308/6489574/960890bc-c25c-11e4-81ba-24c385ac6cd8.png)

The visible source also felt a little small in comparison to the other sources, so I have made it a bit larger (again, while maintaining the same overall width). The updated artwork has been emailed to @jessegreenberg to implement.

**Comment by jessegreenberg** [comment]
New images for visible and microwave emitters have been added in version dev.8.  I have also updated the assets file to reflect changes to the artwork.  Reassigning to @arouinfar for review.

**Comment by arouinfar** [comment]
It looks great! Thanks, @jessegreenberg. Closing.
