### ISSUE TITLE
Photon spacing is incorrect in some situations

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#97]
On iPad 2 and 3, the spacing of the photons can often be made to be uneven by starting the photons flowing, then pausing and un-pausing the sim several times.  See screenshot below.

![mal-photon-spacing](https://cloud.githubusercontent.com/assets/3082831/6604500/58039b94-c7ee-11e4-9a82-8965558fbf20.PNG)

**Comment by jbphet** [comment]
I have not seen this exact behavior on other hardware, but on Win7+Chrome it does seem like the rightmost photon in a stream of photons often seems to "jump" a bit.  I think it may actually be a pause in its forward motion, but it is noticeable.  This may be a separate issue, but I'm keeping them together for now and will split out if one is fixed and the other still exists.

**Comment by jbphet** [comment]
The version used for this testing was http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.8/molecules-and-light_en.html.

**Comment by jbphet** [comment]
After some investigation, I think there are two separate problems here.  The issue described in one of the comments about about a "jump" in the photon position was actually a pause in its position while the other photons moved around it.  This appears to have been due to a bug with some loop index values.  The errant loops were fixed, and I'm not seeing the behavior anymore.  The problem reported at the top of this issue, which is specific to iPad, is not yet fixed.

**Comment by jbphet** [comment]
This problem was due to the occasional "big time step" on the iPad.  A big step could cause a photon to be emitted and then moved with existing photons in a single step.  Reversing the order of emitting and moving, plus advancing the newly emitted by the appropriate amount, addresses the problem.  Assigning to @jessegreenberg to review.

**Comment by jessegreenberg** [comment]
Excellent, thanks very much @jbphet, just tested on my iPad2 and I can no longer reproduce the issue.  Closing.
