### ISSUE TITLE
Optimization ideas

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#98]
Discussed these yesterday with @jessegreenberg and thought it would be good to capture them.  Here are several things that we should consider pursuing as we work on improving the performance of this sim:

+ Try replacing halos with something that has no transparency.  @jonathanolson indicated that transparency often causes layer splits in Scenery, so it would be good to remove these splits and test to see if it makes a significant difference in the performance.
+ Try using pools of photon and atom nodes instead of allocating them and adding/removing them to/from the scene graph.  A lot of the glitchy behavior on iPads seems to occur when nodes are being removed from the scene graph, so this could make a big difference.
+ There are a lot of vector allocations that occur as particles move on the screen, which means that there is a lot of garbage collection.  We could investigate having the particles use numbers for x and y positions, or a mutable vector, and signal movement using events.
+ WebGL with canvas fallback could be used as the rendering surface for photons and particles.  This would be a fair amount of work, though, and more difficult to maintain, so this should probably be seen as a bit of a last resort.

**Comment by jbphet** [comment]
During yesterday's discussion, @jessegreenberg agreed that he would try removing the halo and see how much the Block Summary changes and whether the frame rate increases significantly on the iPad.  This is the Block Summary from version http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.8/molecules-and-light_en.html just after startup.  @jonathanolson says that this is big, likely due to the use of transparency in each atom.

Display Summary
[742w, 961h] frame:1363 input:true cursor:default
Nodes: 268
Instances: 268
Drawables: 219
Block Summary
#195
SVGBlock#20-commonAncestor (14 drawables)
CanvasBlock#21-commonAncestor (1 drawables)
SVGBlock#196-commonAncestor (10 drawables)
#197
SVGBlock#38-commonAncestor (2 drawables)
SVGBlock#198-commonAncestor (3 drawables)
#199
SVGBlock#44-commonAncestor (1 drawables)
#200
SVGBlock#48-commonAncestor (2 drawables)
SVGBlock#201-commonAncestor (1 drawables)
#202
SVGBlock#52-commonAncestor (1 drawables)
SVGBlock#203-commonAncestor (5 drawables)
#204
SVGBlock#60-commonAncestor (1 drawables)
#205
SVGBlock#64-commonAncestor (2 drawables)
SVGBlock#206-commonAncestor (1 drawables)
#207
SVGBlock#68-commonAncestor (1 drawables)
#208
SVGBlock#71-commonAncestor (1 drawables)
#209
SVGBlock#75-commonAncestor (2 drawables)
SVGBlock#210-commonAncestor (1 drawables)
#211
SVGBlock#79-commonAncestor (1 drawables)
SVGBlock#212-commonAncestor (12 drawables)
#213
SVGBlock#94-commonAncestor (1 drawables)
#214
SVGBlock#105-commonAncestor (9 drawables)
SVGBlock#215-commonAncestor (1 drawables)
#216
SVGBlock#109-commonAncestor (1 drawables)
#217
SVGBlock#119-commonAncestor (8 drawables)
SVGBlock#218-commonAncestor (1 drawables)
#219
SVGBlock#123-commonAncestor (1 drawables)
#220
SVGBlock#136-commonAncestor (11 drawables)
SVGBlock#221-commonAncestor (1 drawables)
#222
SVGBlock#140-commonAncestor (1 drawables)
#223
SVGBlock#151-commonAncestor (9 drawables)
SVGBlock#224-commonAncestor (1 drawables)
#225
SVGBlock#155-commonAncestor (1 drawables)
#226
SVGBlock#167-commonAncestor (10 drawables)
SVGBlock#227-commonAncestor (1 drawables)
#228
SVGBlock#171-commonAncestor (1 drawables)
#229
SVGBlock#183-commonAncestor (10 drawables)
SVGBlock#230-commonAncestor (5 drawables)

**Comment by jbphet** [comment]
Assigning to @jessegreenberg for next steps.

**Comment by jessegreenberg** [comment]
Version dev.9 has been published as a version with halo gradients completely removed from the sim.

The following is a quick report of profiler results on versions dev.8 (halos included) and dev.9 (halos removed), tested on iPad2 (iOS 8.1.3).

dev.9 (halo gradients removed):
    29 FPS - 34 ms/frame 

dev.8(halo gradients included):
    23 FPS - 43 ms/frame

**Comment by jessegreenberg** [comment]
Here is the scenery debug snapshot produced by popupDebug with version dev.9 (halos removed)

Display Summary
[882w, 947h] frame:5229 input:true cursor:default
Nodes: 279
Instances: 279
Drawables: 228

Block Summary
DOMBlock#195
SVGBlock#20-commonAncestor (12 drawables)
DOMBlock#207
SVGBlock#64-commonAncestor (1 drawables)
SVGBlock#68-commonAncestor (6 drawables)
CanvasBlock#21-commonAncestor (1 drawables)
SVGBlock#196-commonAncestor (10 drawables)
DOMBlock#197
SVGBlock#38-commonAncestor (2 drawables)
SVGBlock#198-commonAncestor (3 drawables)
DOMBlock#199
SVGBlock#44-commonAncestor (1 drawables)
DOMBlock#200
SVGBlock#48-commonAncestor (2 drawables)
SVGBlock#201-commonAncestor (1 drawables)
DOMBlock#202
SVGBlock#52-commonAncestor (1 drawables)
DOMBlock#204
SVGBlock#60-commonAncestor (1 drawables)
DOMBlock#243
SVGBlock#240-commonAncestor (2 drawables)
SVGBlock#203-commonAncestor (1 drawables)
DOMBlock#245
SVGBlock#242-commonAncestor (1 drawables)
SVGBlock#244-commonAncestor (5 drawables)
DOMBlock#208
SVGBlock#71-commonAncestor (1 drawables)
DOMBlock#209
SVGBlock#75-commonAncestor (2 drawables)
SVGBlock#210-commonAncestor (1 drawables)
DOMBlock#211
SVGBlock#79-commonAncestor (1 drawables)
SVGBlock#212-commonAncestor (3 drawables)
DOMBlock#225
SVGBlock#155-commonAncestor (1 drawables)
DOMBlock#205
SVGBlock#206-commonAncestor (7 drawables)
SVGBlock#254-commonAncestor (1 drawables)
DOMBlock#213
SVGBlock#94-commonAncestor (1 drawables)
DOMBlock#214
SVGBlock#105-commonAncestor (9 drawables)
SVGBlock#215-commonAncestor (1 drawables)
DOMBlock#216
SVGBlock#109-commonAncestor (1 drawables)
DOMBlock#217
SVGBlock#119-commonAncestor (8 drawables)
SVGBlock#218-commonAncestor (1 drawables)
DOMBlock#219
SVGBlock#123-commonAncestor (1 drawables)
DOMBlock#220
SVGBlock#136-commonAncestor (11 drawables)
SVGBlock#221-commonAncestor (1 drawables)
DOMBlock#222
SVGBlock#140-commonAncestor (1 drawables)
DOMBlock#223
SVGBlock#151-commonAncestor (9 drawables)
SVGBlock#224-commonAncestor (13 drawables)
DOMBlock#228
SVGBlock#171-commonAncestor (1 drawables)
DOMBlock#229
SVGBlock#183-commonAncestor (10 drawables)
SVGBlock#230-commonAncestor (5 drawables)

**Comment by jessegreenberg** [comment]
Version dev.9 seems to offer slightly higher FPS, but I see very little change in the block summary with halo gradients removed.

**Comment by jbphet** [comment]
I just compared the number of blocks in the first block summary to the second and the second actually appears to have more blocks - 60 versus 59 - so removing the node that was using opacity doesn't seem to have reduced the number of blocks at all.

I dug into this a bit, and found the following in the "Root Instance Tree" portion of the popupDebug window.  I was searching for "opacity", hence the highlighted words.

![mal-opacity-in-scene-graph](https://cloud.githubusercontent.com/assets/3082831/6643380/5307d8e2-c971-11e4-9d1d-51f356f36f83.png)

This would seem to indicate that there are still a lot of places where opacity is being used, I thought I'd try to track them down.  Ultimately, I found that opacity is used extensively in the RadioButtonGroupMember and RadioButtonGroup classes.  I tried setting all of the opacity values for fields such as ```selectedButtonOpacity``` in these classes to 1, and here is what the block summery looked like:

Block Summary
DOMBlock#153
SVGBlock#20-commonAncestor (14 drawables)
CanvasBlock#21-commonAncestor (1 drawables)
SVGBlock#154-commonAncestor (10 drawables)
DOMBlock#155
SVGBlock#38-commonAncestor (2 drawables)
SVGBlock#156-commonAncestor (108 drawables)

Yowza - that's a big reduction, from ~60 to 7.  So apparently @jonathanolson's observation that the use of opacity may be causing a deep scene graph is true, but it's not because of code in Molecules and Light, it's because of common code.  The next step, I suppose, is to see if this results in better performance on iPad.

**Comment by jbphet** [comment]
Based on data collected here https://github.com/phetsims/tasks/issues/192 is doesn't seem like getting rid of opacity makes a big performance difference on an iPad 3.  We should discuss this with @jonathanolson to see if he is surprised by this, and to determine which things to try next.

**Comment by jbphet** [comment]
@jessegreenberg and I looked at the issues with @jonathanolson, and he has logged two issues for Scenery (see links just above this comment) that should make the performance better in the problem cases that we are observing.

**Comment by jbphet** [comment]
Performance has been tested on tablets based on the recent changes, and has been judged to be sufficient, see #91 and #93.  Closing.
