### ISSUE TITLE
Clipping area isn't clipping atoms as expected

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#99]
The edges of atoms can sometimes be seen outside the viewport frame when atoms break apart.  This can be seen in the screen shots below.  These was originally noticed on iPad and reproduced on Chrome.  The version being tested was http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.8/molecules-and-light_en.html.

It would appear that something is not set up quite right with the clipping region.

![mal-clipping-2](https://cloud.githubusercontent.com/assets/3082831/6604798/b93cc62c-c7f0-11e4-90cb-6b2919eac249.png)

![mal-clipping-1](https://cloud.githubusercontent.com/assets/3082831/6604802/c1660318-c7f0-11e4-97a7-06a48f048286.png)

**Comment by jessegreenberg** [comment]
While investigating this on Chrome and iPad2 (iOS 8.2) I notice two things:

1) The clipping area will behave well when molecule removal does not set the 'Return Molecule' button opacity.

2) I can no longer reproduce this issue after commit ff3a26b6949397481e1cce896c8b404fe371b6d3.

The workaround referenced in issue #98 seems to have resolved this, reassigning to @jbphet for review.

**Comment by jessegreenberg** [comment]
I have moved the WindowFrameNode into MoleculesAndLightScreenView, which restricted the clipping area of the Observation Window.  This should improve behavior of the clipping area.

**Comment by jbphet** [comment]
Tested on iPad, Chrome+Win7, and Firefox+Win7, and it looks much better in all cases.  Closing.
